packages/contentstack-bulk-publish/package.json, packages/contentstack-bulk-publish/src/commands/cm/bulk-publish/cross-publish.js, packages/contentstack-bulk-publish/src/commands/cm/bulk-publish/unpublish.js, packages/contentstack-bulk-publish/src/producer/cross-publish.js, packages/contentstack-bulk-publish/src/producer/unpublish.js, packages/contentstack/package.json
Description: 
This is a fix for the issue where assets were not getting published while using the cross publish command.
This command uses the sync api for publishing both assets and entries, the problem was that the `type` paramter, in the 
`filter` query parameter needed to be left empty for publishing both entries and assets.
Here is the relevant [ticket](https://contentstack.atlassian.net/browse/CS-18803)
=> fix: added a fix for assets not being published

packages/contentstack-clone/package.json, packages/contentstack-clone/src/commands/cm/stack-clone.js, packages/contentstack/package.json
Description:
Fix for the issue where, upon cancelling a stack clone command operation mid import, the temporary files weren't being cleared. Due to this, when the stack clone command is run another time, the old temporary also gets imported.
Here is the relevant [ticket](https://contentstack.atlassian.net/browse/CS-18825)
=> fix: added clean up for temp files

.talismanrc, packages/contentstack-import/package-lock.json, packages/contentstack-import/package.json, packages/contentstack-import/src/lib/import/entries.js, packages/contentstack-import/src/lib/util/supress-mandatory-fields.js, packages/contentstack/package-lock.json, packages/contentstack/package.json
Added a fix for an issue faced while importing entries, where `reference_to` property of a reference field should ban array
ticket id: CS-21058
=> fix: reference_to must be an array

packages/contentstack-seed/src/commands/cm/stacks/seed.ts, packages/contentstack-seed/src/seed/index.ts, packages/contentstack-seed/src/seed/interactive.ts
Code smell fixes
- 'flags' is already declared in the upper scope.
- Expected an assignment or function call and instead saw an expression.
- Immediately return this expression instead of assigning it to the temporary variable "response"
- Redundent use of 'await' on a return value
=> SRE seed fixes - CS-28492

packages/contentstack-import/src/commands/cm/stacks/import.js, packages/contentstack-import/src/lib/import/entries.js
Declared `self` variable and fix deprecation warning for backup-dir flag
=> fix: declared self and fixed deprecation warning

packages/contentstack-bootstrap/src/commands/cm/bootstrap.ts
- added a condition so that live preview confirmation is not asked after passing the `--yes` flag
=> fix: added fix for livePreview confirmation

packages/contentstack-clone/src/lib/util/clone-handler.js
This PR fixes CS-39538 and CS-39565.
=> fix(clone): fixed target branches issue

packages/contentstack-branches/src/utils/entry-create-script.ts, packages/contentstack-branches/src/utils/entry-create-update-script.ts, packages/contentstack-branches/src/utils/entry-update-script.ts
=> Updating the Entry Migration script to perform the merge operation on entries

package-lock.json, packages/contentstack-branches/package.json, packages/contentstack-branches/src/utils/entry-create-script.ts, packages/contentstack-branches/src/utils/entry-create-update-script.ts, packages/contentstack-branches/src/utils/entry-update-script.ts, packages/contentstack/package.json, pnpm-lock.yaml
=> CLI | Error in the Entry Migration script

packages/contentstack-export/src/config/index.ts, packages/contentstack-export/src/export/modules/taxonomies.ts, packages/contentstack-export/src/types/default-config.ts, packages/contentstack-export/src/types/index.ts
=> Add Taxonomy module to CLI Export Plugin

packages/contentstack-import/src/import/modules/content-types.ts, packages/contentstack-import/src/import/modules/entries.ts, packages/contentstack-import/src/import/modules/taxonomies.ts, packages/contentstack-import/src/utils/index.ts, packages/contentstack-import/src/utils/taxonomies-helper.ts
=> Import content types and entries module supports taxonomy

packages/contentstack-export-to-csv/src/util/index.js
=> Sanitize taxonomies & terms data against csv injection

.github/workflows/release.yml, package-lock.json, packages/contentstack-audit/package.json, packages/contentstack-audit/src/messages/index.ts, packages/contentstack-audit/src/modules/content-types.ts, packages/contentstack/package.json, pnpm-lock.yaml
=> Feat: Audit Release workflow added, UI text fixes

packages/contentstack-audit/src/audit-base-command.ts, packages/contentstack-audit/src/messages/index.ts, packages/contentstack-audit/src/modules/content-types.ts
=> Feat: Global field audit:fix functionality added

package-lock.json, packages/contentstack-export/src/export/modules-js/marketplace-apps.js, packages/contentstack-export/src/export/modules/marketplace-apps.ts, packages/contentstack-export/src/utils/file-helper.ts, packages/contentstack-export/src/utils/marketplace-app-helper.ts, pnpm-lock.yaml
=> Fix: Export - Cannot read properties of undefined (reading 'encrypt')

packages/contentstack-export/src/export/module-exporter.ts, packages/contentstack-import/src/import/modules/entries.ts
=> fixed entry overwrite issues

package-lock.json, packages/contentstack-export-to-csv/src/commands/cm/export-to-csv.js, packages/contentstack-export-to-csv/src/util/index.js, packages/contentstack-export-to-csv/test/unit/commands/export-to-csv.test.js, packages/contentstack-export/src/config/index.ts, packages/contentstack-export/src/export/modules/taxonomies.ts, packages/contentstack-import/package.json, packages/contentstack-import/src/import/modules/base-class.ts, packages/contentstack-import/src/import/modules/taxonomies.ts, packages/contentstack-utilities/package.json, packages/contentstack/package.json, pnpm-lock.yaml
=> Taxonomy | Replace http calls with SDK calls

packages/contentstack-audit/README.md, packages/contentstack-audit/package.json, packages/contentstack-audit/src/audit-base-command.ts, packages/contentstack-audit/src/commands/cm/stacks/audit/fix.ts, packages/contentstack-audit/src/commands/cm/stacks/audit/index.ts, packages/contentstack-audit/src/messages/index.ts, packages/contentstack-audit/src/modules/content-types.ts, packages/contentstack-audit/src/modules/entries.ts, packages/contentstack-audit/src/types/content-types.ts, packages/contentstack-audit/src/types/entries.ts, packages/contentstack/README.md
=> Feat: Audit fix command for entry

packages/contentstack-export/src/export/modules/marketplace-apps.ts, packages/contentstack-export/src/types/index.ts, packages/contentstack-export/src/types/marketplace-app.ts, packages/contentstack-export/src/utils/marketplace-app-helper.ts, packages/contentstack-export/test/unit/export/modules/marketplace-apps.test.ts, packages/contentstack-utilities/src/contentstack-marketplace-sdk.ts, packages/contentstack-utilities/src/index.ts
**CS-42903**
**NOTE**: As the new marketplace app SDK release is required, so version bump will be done later.
=> refactor: export marketplace apps HTTP adapter calls to SDK call migration [CS-42903]

packages/contentstack-audit/src/audit-base-command.ts, packages/contentstack-audit/src/base-command.ts, packages/contentstack-audit/src/commands/cm/stacks/audit/fix.ts, packages/contentstack-audit/src/types/utils.ts, packages/contentstack-audit/src/util/flags.ts, packages/contentstack-utilities/src/index.ts
=> Feat: New hidden flag introduced to accept json data [CS-43198]

package-lock.json, packages/contentstack-branches/README.md, packages/contentstack-branches/package.json, packages/contentstack-branches/src/utils/entry-create-script.ts, packages/contentstack-branches/src/utils/entry-create-update-script.ts, packages/contentstack-branches/src/utils/entry-update-script.ts, packages/contentstack/package.json, pnpm-lock.yaml
version bump:
@contentstack/cli-cm-branches: 1.0.20 -> 1.0.21
=> CS-43272- GCP changes for branches plugin

package-lock.json, packages/contentstack-launch/src/adapters/github.ts, packages/contentstack-launch/src/base-command.ts, packages/contentstack-launch/src/commands/launch/deployments.ts, packages/contentstack-launch/src/commands/launch/environments.ts, packages/contentstack-launch/src/commands/launch/functions.ts, packages/contentstack-launch/src/commands/launch/index.ts, packages/contentstack-launch/src/commands/launch/logs.ts, packages/contentstack-launch/src/commands/launch/open.ts, packages/contentstack-launch/src/config/index.ts, pnpm-lock.yaml
=> refactor: Launch base class refactor

package-lock.json, packages/contentstack-audit/package.json, packages/contentstack-audit/src/audit-base-command.ts, packages/contentstack-audit/src/modules/content-types.ts, packages/contentstack-audit/src/modules/entries.ts, packages/contentstack-import/package.json, packages/contentstack/package.json, pnpm-lock.yaml
=> refactor: Handle file/folder missing case

package-lock.json, packages/contentstack-config/README.md, packages/contentstack-config/package.json, packages/contentstack/README.md, packages/contentstack/package.json, pnpm-lock.yaml
@contentstack/cli 1.13.2 -> 1.13.3
@contentstack/cli-config  1.6.1 -> 1.6.2
Note:- @contentstack/cli version already bumped to 1.13.2 for hotfix. #1279
=> Sprint 51 version bump

package-lock.json, packages/contentstack-export/README.md, packages/contentstack-export/package.json, packages/contentstack-export/src/config/index.ts, packages/contentstack-export/src/export/modules/base-class.ts, packages/contentstack-export/src/export/modules/taxonomies.ts, packages/contentstack-export/src/types/default-config.ts, packages/contentstack-export/src/types/index.ts, packages/contentstack-import/package.json, packages/contentstack-utilities/package.json, packages/contentstack/package.json, pnpm-lock.yaml
@contentstack/cli-cm-export 1.10.5 -> 1.11.0
@contentstack/management 1.13.0 -> 1.15.1
**NOTE:-** Created a base branch as API isn't released yet.
=> Export | Taxonomy | Replace taxonomy all terms api with export api

packages/contentstack-export/src/commands/cm/stacks/export.ts, packages/contentstack-export/src/utils/logger.ts
=> CS-43741-handled why logs where not created in mentioned path

package-lock.json, packages/contentstack-audit/package.json, packages/contentstack-auth/package.json, packages/contentstack-bootstrap/package.json, packages/contentstack-branches/package.json, packages/contentstack-bulk-publish/package.json, packages/contentstack-clone/package.json, packages/contentstack-command/package.json, packages/contentstack-config/package.json, packages/contentstack-export-to-csv/package.json, packages/contentstack-export/package.json, packages/contentstack-import/package.json, packages/contentstack-launch/package.json, packages/contentstack-migrate-rte/package.json, packages/contentstack-migration/package.json, packages/contentstack-seed/package.json, packages/contentstack-utilities/package.json, packages/contentstack-utilities/src/auth-handler.ts, pnpm-lock.yaml
version bump:
@contentstack/cli-utilities: 1.5.12 -> 1.4.13
=> CS-42790- Replaced PseudoRandomBytes with RandomBytes

package-lock.json, packages/contentstack-clone/package.json, packages/contentstack-import/package.json, packages/contentstack-import/src/import/modules/base-class.ts, packages/contentstack-import/src/import/modules/content-types.ts, packages/contentstack-import/src/import/modules/extensions.ts, packages/contentstack-import/src/types/index.ts, packages/contentstack-seed/package.json, packages/contentstack/package.json, pnpm-lock.yaml
version bump:
@contentstack/cli-cm-import: 1.13.4 -> 1.13.5
=> CS-43639-added update the extension after the creation of content types and version bump

packages/contentstack-import/src/commands/cm/stacks/import.ts, packages/contentstack-import/src/import/module-importer.ts, packages/contentstack-import/src/types/import-config.ts
version bump:
Already done in #1300  and will go in same release
=> CS-43987-added stack name to the config

package-lock.json, package.json, pnpm-lock.yaml
=> Refactor: package-lock update script and cache clear scripts added [CS-44108]

package-lock.json, packages/contentstack-audit/package.json, packages/contentstack-audit/src/config/index.ts, packages/contentstack-clone/package.json, packages/contentstack-import/package.json, packages/contentstack-import/src/config/index.ts, packages/contentstack-import/src/import/module-importer.ts, packages/contentstack-import/src/types/default-config.ts, packages/contentstack-seed/package.json, packages/contentstack/package.json, pnpm-lock.yaml
**CS-44077**
Version bump is done?
=> Fix: Audit group field removal issue fix

package-lock.json, packages/contentstack-audit/package.json, packages/contentstack-audit/src/audit-base-command.ts, packages/contentstack-audit/src/messages/index.ts, packages/contentstack-audit/src/modules/workflows.ts, packages/contentstack-audit/src/types/content-types.ts, packages/contentstack-audit/src/types/workflow.ts, packages/contentstack-audit/test/unit/mock/contents/workflows/workflows.json, packages/contentstack-audit/test/unit/modules/workflow.test.ts, packages/contentstack-import/package.json, packages/contentstack-import/src/import/module-importer.ts, packages/contentstack-import/src/types/default-config.ts, packages/contentstack/package.json, pnpm-lock.yaml
Added the check to remove all the other branches than the one mentioned in the import and while doing audit we can pass branch to be kept using config flag and version bump currently only for workflows
version bump:
@contentstack/cli-audit: 1.5.0 -> 1.5.1
=> CS-44350 - Added support for removing the branches that are not being exported in the workflows

packages/contentstack-audit/src/messages/index.ts, packages/contentstack-audit/src/modules/extensions.ts, packages/contentstack-audit/src/modules/workflows.ts, packages/contentstack-import/src/import/module-importer.ts
=> Merge staging to development

packages/contentstack-audit/src/audit-base-command.ts, packages/contentstack-audit/src/modules/extensions.ts, packages/contentstack-audit/src/modules/workflows.ts, packages/contentstack-migration/src/utils/error-helper.js
Removed the request body from error in the migration loggers
=> CS-44565 - Resolved issue when content not overwritten in import backup folder when using audit fix with import

package-lock.json, packages/contentstack-audit/src/audit-base-command.ts, packages/contentstack-audit/src/config/index.ts, packages/contentstack-audit/src/messages/index.ts, packages/contentstack-audit/src/modules/entries.ts, packages/contentstack-audit/src/types/content-types.ts, packages/contentstack-audit/src/types/entries.ts
added audit and audit fix for mandatory fields in Entries, and added logs for fix Select fields lock-file update
Version bump:
Done in Development
=> DX - 523 - Audit and Audit Fix for Mandatory Fields

packages/contentstack-import/src/utils/asset-helper.ts
=> fix: issue with import entries arising from compact library

package-lock.json, packages/contentstack-branches/package.json, packages/contentstack-branches/src/utils/entry-create-script.ts, packages/contentstack-branches/src/utils/entry-create-update-script.ts, packages/contentstack-branches/src/utils/entry-update-script.ts, packages/contentstack/package.json, pnpm-lock.yaml
version bump:
@contentstack/cli: 1.18.2 -> 1.19.0
@contentstack/cli-cm-branches: 1.0.26 -> 1.1.0
=> fix: Handled pagination during the script creation

packages/contentstack/bin/run.js
=> fix: handle deprecation warning message

package-lock.json, packages/contentstack-audit/package.json, packages/contentstack-auth/package.json, packages/contentstack-bootstrap/package.json, packages/contentstack-branches/package.json, packages/contentstack-bulk-publish/package.json, packages/contentstack-clone/package.json, packages/contentstack-command/package.json, packages/contentstack-config/package.json, packages/contentstack-export-to-csv/package.json, packages/contentstack-export/package.json, packages/contentstack-import/package.json, packages/contentstack-launch/package.json, packages/contentstack-migrate-rte/package.json, packages/contentstack-migration/package.json, packages/contentstack-seed/package.json, packages/contentstack-utilities/package.json, packages/contentstack/package.json, pnpm-lock.yaml
- upgraded contentstack/cli-utilities in each plugin 1.6.2 -> 1.6.3
- removed 'upgrade'  dependency from contentstack/cli-utilities
=> version bump

package-lock.json, packages/contentstack-clone/package.json, packages/contentstack-import/README.md, packages/contentstack-import/package.json, packages/contentstack-import/src/import/modules/environments.ts, packages/contentstack-import/src/import/modules/taxonomies.ts, packages/contentstack-seed/package.json, packages/contentstack/package.json, pnpm-lock.yaml
=> fix: handle taxonomy & environment mapper issue

package-lock.json, packages/contentstack-import/package.json, packages/contentstack-migrate-rte/package.json, packages/contentstack-migration/README.md, packages/contentstack-migration/package.json, packages/contentstack-migration/src/commands/cm/stacks/migration.js, packages/contentstack-migration/src/utils/index.js, packages/contentstack-migration/src/utils/modules.js, packages/contentstack-utilities/package.json, packages/contentstack/README.md, packages/contentstack/package.json, pnpm-lock.yaml
version bump:
@contentstack/cli: 1.20.0 -> 1.21.0
@contentstack/cli-migration: 1.5.6 -> 1.6.0
=> DX - 77: Added the missing modules handle function, upgraded uuid and version bump

package-lock.json, packages/contentstack-launch/README.md, packages/contentstack-launch/package.json, packages/contentstack-launch/src/adapters/base-class.ts, packages/contentstack-launch/src/adapters/file-upload.ts, packages/contentstack-launch/src/adapters/github.ts, packages/contentstack-launch/src/commands/launch/index.ts, packages/contentstack-launch/src/config/index.ts, packages/contentstack/package.json, pnpm-lock.yaml
=> feat: added flag to support variable types & respective prompt

packages/contentstack-launch/src/commands/launch/index.ts
=> refactor: launch create command ui text

package-lock.json, packages/contentstack-audit/package.json, packages/contentstack-auth/package.json, packages/contentstack-bootstrap/package.json, packages/contentstack-branches/package.json, packages/contentstack-bulk-publish/package.json, packages/contentstack-clone/package.json, packages/contentstack-command/package.json, packages/contentstack-config/package.json, packages/contentstack-export-to-csv/package.json, packages/contentstack-export/package.json, packages/contentstack-import/README.md, packages/contentstack-import/package.json, packages/contentstack-launch/package.json, packages/contentstack-migrate-rte/package.json, packages/contentstack-migration/package.json, packages/contentstack-seed/package.json, packages/contentstack-utilities/package.json, packages/contentstack/README.md, packages/contentstack/package.json, pnpm-lock.yaml
version bump:
@contentstack/cli-utilities: 1.7.0 -> 1.7.1
@contentstack/cli-cm-import: 1.16.2 -> 1.16.3
@contentstack/cli: 1.21.0 -> 1.21.1
@contentstack/management: 1.15.3 -> 1.17.0
=> Updated management SDK version and version bump

package-lock.json, packages/contentstack-clone/package.json, packages/contentstack-import/README.md, packages/contentstack-import/package.json, packages/contentstack-import/src/import/modules/marketplace-apps.ts, packages/contentstack-import/src/utils/interactive.ts, packages/contentstack-seed/package.json, packages/contentstack/README.md, packages/contentstack/package.json, pnpm-lock.yaml
"@contentstack/cli-cm-import": 1.16.2 -> "~1.16.3",
@contentstack/cli: 1.21.0 -> 1.21.1
=> fix: handle name conflict in case of custom extension

package-lock.json, packages/contentstack-branches/package.json, packages/contentstack-config/README.md, packages/contentstack-config/package.json, packages/contentstack-config/src/commands/config/get/region.ts, packages/contentstack-config/src/commands/config/set/region.ts, packages/contentstack-config/src/interfaces/index.ts, packages/contentstack-config/src/utils/region-handler.ts, packages/contentstack-config/test/unit/commands/region.test.ts, packages/contentstack-export/package.json, packages/contentstack/package.json, pnpm-lock.yaml
- version bump to be made
- set and get personalization and developer hub url
=> dx | 562 set get personalization and developer hub url

package-lock.json, packages/contentstack-audit/README.md, packages/contentstack-audit/package.json, packages/contentstack-audit/src/audit-base-command.ts, packages/contentstack-audit/src/config/index.ts, packages/contentstack-audit/src/messages/index.ts, packages/contentstack-audit/src/modules/custom-roles.ts, packages/contentstack-audit/src/types/custom-role.ts, packages/contentstack-audit/src/types/index.ts, packages/contentstack-import/README.md, packages/contentstack-import/package.json, packages/contentstack-import/src/import/module-importer.ts, packages/contentstack-import/src/utils/import-config-handler.ts, packages/contentstack-seed/package.json, packages/contentstack/README.md, packages/contentstack/package.json, pnpm-lock.yaml
@contentstack/cli-audit": 1.6.5 -> "~1.7.0"
@contentstack/cli-cm-import": 1.6.6 -> "~1.16.7",
=> feat: add custom role support in audit plugin

packages/contentstack-audit/src/audit-base-command.ts, packages/contentstack-audit/src/config/index.ts, packages/contentstack-audit/src/modules/entries.ts, packages/contentstack-audit/src/types/content-types.ts
=> Fix/dx 1313 - Created seperate file empty Title Field 

packages/contentstack-config/src/commands/config/get/rate-limit.ts, packages/contentstack-config/src/commands/config/remove/rate-limit.ts, packages/contentstack-config/src/interfaces/index.ts, packages/contentstack-config/src/utils/interactive.ts
- get rate limit command
- remove rate limit command
- version bump to be made
=> dx | 1201 | get and remove rate limit commands

packages/contentstack-config/README.md, packages/contentstack-config/src/commands/config/set/rate-limit.ts, packages/contentstack-config/src/utils/rate-limit-handler.ts, packages/contentstack-config/test/unit/commands/rate-limit.test.ts, packages/contentstack/README.md
- Set rate limit command test case
- Get rate limit command test case
- Remove rate limit command test case
=> dx | 1203 test cases rate limit command

package-lock.json, packages/contentstack-auth/src/commands/auth/login.ts, packages/contentstack-branches/package.json, packages/contentstack-branches/src/utils/entry-create-script.ts, packages/contentstack-branches/src/utils/entry-create-update-script.ts, packages/contentstack-branches/src/utils/entry-update-script.ts, packages/contentstack-variants/.gitignore, packages/contentstack/package.json, pnpm-lock.yaml
version bump:
@contentstack/cli-cm-branches: 1.1.3 --> 1.2.0
=> fixed the asset in custom extension

packages/contentstack-config/test/unit/commands/base-branch.test.ts, packages/contentstack-config/test/unit/commands/early-access-header.test.ts, packages/contentstack-config/test/unit/commands/region.test.ts
- updated current test cases according to oclif changes
- added few test cases to improve code coverage reports
=> dx | 1343 config plugin test cases

packages/contentstack-import-setup/src/config/index.ts, packages/contentstack-import-setup/src/import/modules/taxonomies.ts, packages/contentstack-import-setup/src/types/default-config.ts, packages/contentstack-import-setup/src/types/index.ts
=> feat: added taxonomy mapper file support in import setup

package-lock.json, packages/contentstack-audit/package.json, packages/contentstack-auth/messages/index.json, packages/contentstack-bootstrap/package.json, packages/contentstack-branches/package.json, packages/contentstack-bulk-publish/package.json, packages/contentstack-clone/package.json, packages/contentstack-command/package.json, packages/contentstack-config/package.json, packages/contentstack-export-to-csv/package.json, packages/contentstack-export/package.json, packages/contentstack-import-setup/package.json, packages/contentstack-import/README.md, packages/contentstack-import/package.json, packages/contentstack-import/src/import/modules/entries.ts, packages/contentstack-migrate-rte/package.json, packages/contentstack-migration/package.json, packages/contentstack-seed/package.json, packages/contentstack-utilities/package.json, packages/contentstack-utilities/src/auth-handler.ts, packages/contentstack-variants/package.json, packages/contentstack/README.md, packages/contentstack/package.json, pnpm-lock.yaml
@contentstack/cli-cm-import - already done
@contentstack/cli-utilities 1.8.1 -> 1.8.2
=> fix: logout error in Oauth flow

packages/contentstack-import/README.md, packages/contentstack-import/src/commands/cm/stacks/import.ts, packages/contentstack-import/src/config/index.ts, packages/contentstack-import/src/import/modules/assets.ts, packages/contentstack-import/src/import/modules/entries.ts, packages/contentstack-import/src/types/default-config.ts, packages/contentstack-import/src/types/import-config.ts, packages/contentstack-import/src/utils/import-config-handler.ts
=> feat: added skip-assets-publish & skip-entries-publish support in import

package-lock.json, packages/contentstack-audit/README.md, packages/contentstack-audit/package.json, packages/contentstack-audit/src/config/index.ts, packages/contentstack-audit/src/modules/entries.ts, packages/contentstack-audit/src/types/content-types.ts, packages/contentstack-import/package.json, packages/contentstack/README.md, packages/contentstack/package.json, pnpm-lock.yaml
=> DX - 2324 - Feat: Added Support for audit fix to fix select field based on config and added fixedStatus and selected value

.github/workflows/unit-test.yml, package-lock.json, packages/contentstack-audit/package.json, packages/contentstack-audit/test/unit/commands/index.test.ts, pnpm-lock.yaml
=> feat: Add workflow to run and validate unit tests

.github/workflows/unit-test.yml, package-lock.json, packages/contentstack-migrate-rte/README.md, packages/contentstack-migrate-rte/package.json, packages/contentstack-migrate-rte/test/commands/json-migration.test.js, packages/contentstack-migrate-rte/test/dummy/entriesResponse.json, packages/contentstack/package.json, pnpm-lock.yaml
=> test: fix failing cases and added check in workflow

.github/workflows/unit-test.yml, .talismanrc, package-lock.json, packages/contentstack-bootstrap/.eslintrc, packages/contentstack-bootstrap/README.md, packages/contentstack-bootstrap/package.json, packages/contentstack-bootstrap/src/bootstrap/interactive.ts, packages/contentstack-bootstrap/src/bootstrap/utils.ts, packages/contentstack-bootstrap/src/commands/cm/bootstrap.ts, packages/contentstack-bootstrap/test/bootstrap.test.js, packages/contentstack/README.md, packages/contentstack/package.json, pnpm-lock.yaml
=> [DX-2770], fixed failing test cases and added workflow for bootstrap test cases

.talismanrc, packages/contentstack-auth/messages/index.json, packages/contentstack-auth/src/base-command.ts, packages/contentstack-auth/src/commands/auth/login.ts, packages/contentstack-auth/src/commands/auth/logout.ts, packages/contentstack-auth/src/commands/auth/tokens/add.ts, packages/contentstack-auth/src/commands/auth/tokens/index.ts, packages/contentstack-auth/src/commands/auth/tokens/remove.ts, packages/contentstack-auth/src/commands/auth/whoami.ts, packages/contentstack-auth/src/interfaces/index.ts, packages/contentstack-auth/src/utils/auth-handler.ts, packages/contentstack-auth/src/utils/tokens-validation.ts
NOTE:- Will do version bump before releasing this feature to avoid unnecessary version conflict.
=> feat: Integrated Logger and cliErrorHandler in auth plugin

.talismanrc, packages/contentstack-auth/src/base-command.ts, packages/contentstack-export/src/commands/cm/stacks/export.ts, packages/contentstack-export/src/types/export-config.ts, packages/contentstack-export/src/types/index.ts, packages/contentstack-export/src/utils/export-config-handler.ts, packages/contentstack-import/src/commands/cm/stacks/import.ts, packages/contentstack-import/src/types/import-config.ts, packages/contentstack-import/src/types/index.ts, packages/contentstack-import/src/utils/import-config-handler.ts, packages/contentstack-utilities/src/logger/cli-error-handler.ts
**This PR refactors the CLI error handling and updates how authentication metadata is captured in import/export commands.**
Introduces new helper methods (extractClearMessage, streamlined normalization/classification, enhanced metadata extraction) in CLIErrorHandler.
Standardizes authMethod values, makes it optional in config types, and updates context creation in import/export commands.
Renames context identifiers (userId → userUid, organization_uid → oauthOrgUid) and adjusts BaseCommand.
=> refactor: CLI error handling and updates how authentication metadata is captured in import/export commands

.talismanrc, packages/contentstack-config/README.md, packages/contentstack-import/README.md, packages/contentstack-import/src/commands/cm/stacks/import.ts, packages/contentstack/README.md
**Root Cause**
The backupDir variable was only being set after moduleImporter.start() completed successfully. When an error occurred during the import process, this assignment never happened, leaving backupDir as undefined.
=> Fix: Handle undefined backup directory in import plugin when module throws an error

.talismanrc, package-lock.json, packages/contentstack-export-to-csv/package.json, packages/contentstack-export-to-csv/src/commands/cm/export-to-csv.js, packages/contentstack/package.json, pnpm-lock.yaml
=> Fix: Re-initialised the stack client after the branch selection

.talismanrc, package-lock.json, packages/contentstack-clone/package.json, packages/contentstack-export/README.md, packages/contentstack-export/package.json, packages/contentstack-export/src/commands/cm/stacks/export.ts, packages/contentstack/README.md, packages/contentstack/package.json, pnpm-lock.yaml
version bump:
contentstack-export: 1.20.0 -> 1.20.1
contentstack: 1.46.0 -> 1.46.1
=> Fix Removed Character Flag and Version bump
