- .talismanrc
- packages/contentstack-import/package-lock.json
- packages/contentstack/package.json
> Import issue fix

- packages/contentstack-import/package-lock.json
- packages/contentstack-import/package.json
- packages/contentstack-import/src/lib/import/workflows.js
- packages/contentstack/package.json
Resolved issue of CS-23842 - Workflow import is failing
- Added info log to make the user aware that we are skipping importing workflow admin users
- Removed workflow admin users from workflow import payload
> Fixed issue - CS-23842 - Work flow import is failing

- .talismanrc
- packages/contentstack-clone/src/lib/util/clone-handler.js
- packages/contentstack-clone/src/lib/util/contentstack-management-sdk.js
- packages/contentstack-clone/src/lib/util/log.js
- packages/contentstack-export/README.md
**Unresolved issues which might impact the existing code and/or are minor severity:**
- Expected a for-of loop instead of a for loop with this simple iteration
**Horusec:**
- All are false positives
**Gitty leaks/Git Secrets:**
- All are false positives
> SRE issues for clone package

- package-lock.json
- packages/contentstack-migration/package.json
- packages/contentstack/src/hooks/init/utils-init.ts
- packages/contentstack/src/hooks/prerun/auth-guard.ts
- packages/contentstack/src/hooks/prerun/command-deprecation-check.ts
- packages/contentstack/src/utils/context-handler.ts
**Unresolved issues which might impact the existing code and/or are minor severity:**
- Rename this file to "xxxxxClass"
**Horusec:**
- All are false positives
**Gitty leaks/Git Secrets:**
- All are false positives
> SRE issues related to cli package

- .talismanrc
- packages/contentstack-import/src/lib/import/entries.js
- packages/contentstack-import/src/lib/util/lookupReplaceAssets.js
- packages/contentstack-import/src/lib/util/lookupReplaceEntries.js
- packages/contentstack-import/src/lib/util/removeReferenceFields.js
- packages/contentstack-import/src/lib/util/supress-mandatory-fields.js
https://contentstack.atlassian.net/browse/CS-25105
> Hotfix cs 25105

- packages/contentstack-config/package.json
- packages/contentstack-config/src/commands/config/set/region.ts
- packages/contentstack-config/src/utils/interactive.ts
- packages/contentstack-config/src/utils/region-handler.ts
Changes added for azure na region.
> fix: added support for azure NA region

- .talismanrc
- package-lock.json
- package.json
> fix: added fix for npm audit

- packages/contentstack-import/package.json
- packages/contentstack-import/src/lib/import/entries.js
- packages/contentstack-import/src/lib/util/lookupReplaceAssets.js
- packages/contentstack-import/src/lib/util/lookupReplaceEntries.js
Adds a fix for entry refs in Json Rte
https://contentstack.atlassian.net/browse/CS-25105
- https://contentstack.atlassian.net/browse/CS-26567
> Hotfix cs 25105 regression

- packages/contentstack-bulk-publish/src/commands/cm/assets/publish.js
- packages/contentstack-bulk-publish/src/commands/cm/entries/publish.js
- packages/contentstack-bulk-publish/src/commands/cm/stacks/publish.js
- packages/contentstack-bulk-publish/src/util/command-helper.js
Added support for stacks:publish command.
> feat: added stacks publish command

- packages/contentstack-clone/src/commands/cm/stack-clone.js
[Jira Ticket - CS-26888](https://contentstack.atlassian.net/browse/CS-26888)
- When we run the stack clone command, it creates a Content folder in the node module of contentstack. If the stack clone command fails, this folder does not get deleted and when we run the stack clone command again [FIXED]
> Stack clone fix - CS-26888

- packages/contentstack-bulk-publish/src/commands/cm/assets/publish.js
- packages/contentstack-bulk-publish/src/commands/cm/entries/publish.js
- packages/contentstack-bulk-publish/src/commands/cm/stacks/publish.js
1. Fixed bug with entries and assets publish command.
> fix: removed constructor from assets and entries publish command

- packages/contentstack-import/src/lib/import/entries.js
> fix: corrected function parameter

- packages/contentstack-clone/package.json
- packages/contentstack-clone/src/commands/cm/stack-clone.js
- packages/contentstack/package.json
> Lodash dependency removed

- packages/contentstack-clone/src/commands/cm/stacks/clone.js
- packages/contentstack-clone/src/lib/util/clone-handler.js
- Ticket - CS-27117
- Introducing flags in stack-clone command
> GA: Introduce flags in Stack-clone command - CS-27117

- package-lock.json
1. This is a fix for CS-24584.
> fix: added npm audit fixes

- packages/contentstack-export-to-csv/package.json
- packages/contentstack-export-to-csv/src/commands/cm/entries/export-to-csv.js
- packages/contentstack-export-to-csv/src/util/config.js
**Ticket - CS-27130**
-  GA: Introduce flags in Export to CSV command
> GA: Introduce flags in Export to CSV command - CS-27130

- packages/contentstack-bulk-publish/package.json
- packages/contentstack-bulk-publish/src/commands/cm/entries/publish-only-unpublished.js
Warning messages fixes added related to CS-27615.
> fix(bulk-publish): fixed deprecation warning messages

- packages/contentstack-auth/package.json
- packages/contentstack-bootstrap/package.json
- packages/contentstack-command/package.json
- packages/contentstack-config/package.json
- packages/contentstack-seed/package.json
- packages/contentstack/package.json
**Ticket - CS-27756**
- Typescript version update to fix minipass type error
> Typescript MAJOR version update - CS-27756

- packages/contentstack-bootstrap/src/bootstrap/github/client.ts
This PR relates to [CS-25877].
> feat: added a cli specific branch for starter apps

- packages/contentstack-export/src/lib/util/export-flags.js
> fix(export): added fix for content-types flag

- packages/contentstack-bulk-publish/src/commands/cm/bulk-publish/cross-publish.js
> fix(cross-publish): added deprecation warnings and new flags support

- packages/contentstack-bulk-publish/src/util/index.js
> fix(bulk-publish): added proper error handling

- packages/contentstack-import/src/app.js
- Validate if branch exist before importing- CS-28213
> Branch validation added - CS-28213

- packages/contentstack-export/src/commands/cm/stacks/export.js
> fix(export): fixed export usage

- packages/contentstack-export-to-csv/src/commands/cm/export-to-csv.js
- packages/contentstack-export-to-csv/src/util/index.js
- packages/contentstack-import/src/commands/cm/stacks/import.js
- packages/contentstack-import/src/lib/util/import-flags.js
> SRE export CSV fix - CS-28424

- packages/contentstack-bootstrap/src/commands/cm/bootstrap.ts
- packages/contentstack-bootstrap/test/utils.test.js
SRE fixes
- Remove this unused import of 'inquireGithubAccessToken'
- Code smell fix
> Remove this unused import of 'inquireGithubAccessToken' - CS-28457

- packages/contentstack-import/src/app.js
- packages/contentstack-import/src/lib/import/assets.js
- packages/contentstack-import/src/lib/import/entries.js
- packages/contentstack-import/src/lib/util/lookupReplaceAssets.js
Fixes on import files
- Remove this "!==" check; it will always be true. Did you mean to use "!="?
- Unnecessary semicolon.
- Remove the declaration of the unused '_leaf' variable.
- 'e' is already declared in the upper scope.
- 'e' is already declared in the upper scope.
- 'index' is already declared in the upper scope.
- 'element' is already declared in the upper scope.
- 'element' is already declared in the upper scope.
- 'e' is already declared in the upper scope.
- Either use this collection's contents or remove the collection.
- 'entry' is already declared in the upper scope.
- 'e' is already declared in the upper scope.
- 'entry' is already declared in the upper scope.
- 'e' is already declared in the upper scope.
> SRE import fixex - CS-28461

- packages/contentstack-bootstrap/package.json
- packages/contentstack-bootstrap/src/commands/cm/bootstrap.ts
- packages/contentstack-bootstrap/tsconfig.json
- packages/contentstack-seed/package.json
- packages/contentstack-seed/src/commands/cm/seed.ts
- packages/contentstack-seed/tsconfig.json
Lerna prepack issue fixes - CS-28539
- Updated typescript version
- Updated ts config
- Few type fixes
- Code smell fixes
> Lerna prepack issue fixes - CS-28539

- packages/contentstack-auth/messages/index.json
- packages/contentstack-auth/src/commands/auth/tokens/add.ts
- packages/contentstack-auth/src/utils/interactive.ts
> fix: added prompt for token type

- packages/contentstack-import/src/app.js
- packages/contentstack-import/src/lib/import/content-types.js
- packages/contentstack-import/src/lib/util/extensionsUidReplace.js
- packages/contentstack-import/src/lib/util/import-flags.js
**FIX - CS-28566, CS-28614**
- Entries not imported using GA code
- Sonar lint fixes
- Failed to migrate content-types (contentType Uid undefined issue fixes - Filter added)
> Entries not imported using GA code - CS-28566

- packages/contentstack-bootstrap/src/bootstrap/index.ts
- packages/contentstack-bootstrap/src/commands/cm/bootstrap.ts
- packages/contentstack-bootstrap/tsconfig.json
- packages/contentstack-seed/src/commands/cm/stacks/seed.ts
- packages/contentstack-seed/src/seed/index.ts
- packages/contentstack-seed/tsconfig.json
> feat(seed): added support yes flag

- packages/contentstack-export-to-csv/src/util/index.js
**CS-28424**
- RefrenceError: l is not defined - Fixed
> Export to csv refrence error fixes

- packages/contentstack-export/src/lib/export/workflows.js
- packages/contentstack-import/src/lib/import/workflows.js
> feat(roles-support): added support to add roles in workflows and stacks

- packages/contentstack-bootstrap/src/bootstrap/utils.ts
- packages/contentstack-bootstrap/src/config.ts
> feat(bootstrap): added support for vue and stencil apps

- packages/contentstack-clone/src/commands/cm/stacks/clone.js
- packages/contentstack-clone/src/lib/util/abort-controller.js
- packages/contentstack-clone/src/lib/util/clone-handler.js
> fix(stack-clone): added custom abort controller api implementation to support older node versions

- packages/contentstack-export-to-csv/src/commands/cm/export-to-csv.js
**CS-28953**
- Chose language prompt was the last but in the current code Choose Content Type prompt is asked last | Export to CSV prompt(Content-type and language) order correction - Fix
> Export to CSV prompt(Content-type and language) order correction

- packages/contentstack-export/src/lib/export/marketplace-apps.js
- packages/contentstack-import/src/config/default.js
- packages/contentstack-import/src/lib/import/entries.js
- packages/contentstack-import/src/lib/import/global-fields.js
- packages/contentstack-import/src/lib/import/marketplace-apps.js
- packages/contentstack-import/src/lib/util/extensionsUidReplace.js
- packages/contentstack-import/src/lib/util/lookupReplaceAssets.js
CS-29375
- Add marketplace apps support for the global field
- UID replacer/mapper-related fixes
- Prime demo stack import-related fixes
> Add marketplace apps support for global field  - CS-29375

- packages/contentstack-import/src/lib/import/environments.js
- packages/contentstack-import/src/lib/import/extensions.js
- packages/contentstack-import/src/lib/import/global-fields.js
- packages/contentstack-import/src/lib/import/labels.js
- packages/contentstack-import/src/lib/import/locales.js
- packages/contentstack-import/src/lib/import/webhooks.js
- packages/contentstack-import/src/lib/import/workflows.js
added missing require statements
> fix: added missing require statements

- packages/contentstack-utilities/package.json
- packages/contentstack-utilities/src/encrypter.ts
- packages/contentstack-utilities/src/selectors/index.ts
- packages/contentstack-utilities/types/encrypter.d.ts
- packages/contentstack-utilities/types/selectors/index.d.ts
**CS-29320**
- ECYCLE Dependency issue on utility - Fix
- Sprint19 branch Lerna prepack issue - Fix
- Node:crypto package older node version compatibility (Switched package import node:crypto to crypto) - Fix
> Sprint19 branch Lerna prepack issue fix, crypto package version compatibility fix - CS-29320

- packages/contentstack-clone/src/lib/util/clone-handler.js
> fix(stack-clone): added support for marketplace apps in stack clone

- packages/contentstack-clone/src/lib/util/clone-handler.js
- packages/contentstack-export/src/lib/export/marketplace-apps.js
- packages/contentstack-import/src/lib/import/marketplace-apps.js
CS-29461
- Handle auth cases to export/import marketplace apps
- inquire function value access fixes
> Auth warning message added, inquire fixes

- packages/contentstack-export/src/lib/export/marketplace-apps.js
- Missing cliUx utility added in the import section - FIX
> Missing cliUx utility added in the import section

- packages/contentstack-config/src/utils/region-handler.ts
- packages/contentstack-import/test/mock/locales.js
- Inefficient regular expression - CodeQL fix
- Hard-coded credentials- CodeQL Security fix
> Inefficient regular expression - CodeQL fix

- packages/contentstack-import/src/lib/import/custom-roles.js
- packages/contentstack-import/src/lib/import/workflows.js
This PR is a fix for CS-29428.
> fix(workflow-and-custom-roles): handled required branches error

- packages/contentstack-bootstrap/src/bootstrap/index.ts
- packages/contentstack-bootstrap/src/bootstrap/interactive.ts
- packages/contentstack-bootstrap/src/bootstrap/utils.ts
- packages/contentstack-bootstrap/src/commands/cm/bootstrap.ts
> feat(bootstrap): added support to enable live preview

- packages/contentstack-bootstrap/src/commands/cm/bootstrap.ts
> fix(bootstrap): fixed relative path issue

- packages/contentstack-auth/package.json
> fix(auth): parsing message issue hotfix

- packages/contentstack-bootstrap/src/bootstrap/utils.ts
- packages/contentstack-bootstrap/src/commands/cm/bootstrap.ts
This PR resolves CS-29863 and CS-29844.
> fix(bootstrap): help and vuejs bug

- packages/contentstack-export/src/lib/export/marketplace-apps.js
- packages/contentstack-import/src/lib/import/marketplace-apps.js
> Display message corrections

- packages/contentstack-config/src/utils/region-handler.ts
- Inefficient regular expression
- Domain validation fix
> Inefficient regular expression

- package-lock.json
- packages/contentstack-migrate-rte/package.json
> Prepack issue fixed

- packages/contentstack-export/src/config/default.js
- packages/contentstack-export/src/lib/export/marketplace-apps.js
- packages/contentstack-import/src/config/default.js
- packages/contentstack-import/src/lib/import/marketplace-apps.js
Ticket - **CS-30493**
- Add multiple region support for marketplace app URL (Export and Import)
> Multiple region developer hub URL support added

- packages/contentstack-auth/src/commands/auth/tokens/add.ts
- packages/contentstack-auth/src/utils/tokens-validation.ts
- packages/contentstack-command/src/index.ts
This PR resolves CS-29665 and CS-29967.
> skipped validate api key check to support adding mgmt tokens

- packages/contentstack-import/src/lib/import/marketplace-apps.js
- Removed UID from manifest while recreating private app onto an organisation - FIX
> Manifest UID fix

- packages/contentstack-export/src/config/default.js
- packages/contentstack-export/src/lib/export/custom-roles.js
- packages/contentstack-import/src/config/default.js
- packages/contentstack-import/src/lib/import/custom-roles.js
> fix(custom-roles): added support to add rules for locales, entries & envs

- packages/contentstack-export/src/lib/export/marketplace-apps.js
- packages/contentstack-import/src/lib/import/marketplace-apps.js
- Marketplace cosmetic/display message issue fixes
> Fix cs 30728

- packages/contentstack-clone/src/lib/util/clone-handler.js
Ticket - **CS-30889**
- Prompt showing to select branch even if target/source branch already provided - FIX
> Branch selection prompt related fixes

- packages/contentstack-auth/src/utils/tokens-validation.ts
> fix(auth): fixed add delivery token issue

- packages/contentstack-config/src/commands/config/set/region.ts
- packages/contentstack-import/src/app.js
- packages/contentstack-import/src/lib/util/lookupReplaceEntries.js
- packages/contentstack-migration/src/commands/cm/stacks/migration.js
- packages/contentstack-migration/src/modules/migration.js
- packages/contentstack-migration/src/services/content-types.js
- packages/contentstack-migration/src/services/locales.js
- packages/contentstack-migration/src/utils/map.js
- packages/contentstack-utilities/src/config-handler.ts
- packages/contentstack/src/help.ts
Ticket - **CS-31307**
- SonarQube lint issue fixes | Marketplace Integration and Feature Enhancements Release SRE fixes
> SRE sonar lint fixes

- packages/contentstack-import/src/lib/import/marketplace-apps.js
- Update config for public app **_if_** condition mismatch issue fix
> if condition mismatch fixes

- packages/contentstack-bootstrap/src/bootstrap/utils.ts
> fix(bootstrap): fixed angular starter api host issue

- packages/contentstack-bulk-publish/src/commands/cm/bulk-publish/cross-publish.js
- packages/contentstack-clone/test/commands/stack-clone.test.js
- packages/contentstack-config/src/commands/config/set/region.ts
- packages/contentstack-export/test/commands/export.test.js
- packages/contentstack-import/src/lib/util/lookupReplaceEntries.js
- packages/contentstack-import/test/commands/import.test.js
- packages/contentstack-migration/examples/01-transform-contenttype.js
- packages/contentstack-migration/examples/04-create-release-deploy.js
- packages/contentstack-migration/examples/multi-file/01-create-ct-blog.js
- packages/contentstack-migration/test/setup/examples/create-ct/create-ct-chaining.js
- packages/contentstack-migration/test/setup/examples/multifile/01-create-ct-blog.js
- packages/contentstack-utilities/src/config-handler.ts
> fix(code_smell): fixed code smell issues

- packages/contentstack-export/src/config/default.js
- packages/contentstack-export/src/lib/export/global-fields.js
- packages/contentstack-import/src/app.js
- packages/contentstack-import/src/config/default.js
- packages/contentstack-import/src/lib/import/global-fields.js
- Global field stability action points fix/changes
> Global field stability action points fix/changes

- packages/contentstack-export/src/config/default.js
- packages/contentstack-export/src/lib/export/environments.js
- packages/contentstack-import/src/app.js
- packages/contentstack-import/src/lib/import/environments.js
- Environments stability action points fix/changes
> Environments stability

- packages/contentstack-export/src/config/default.js
- packages/contentstack-export/src/lib/export/extensions.js
- packages/contentstack-import/src/lib/import/extensions.js
- Extensions stability action points fix/changes
> Extensions stability

- packages/contentstack-export/src/config/default.js
- packages/contentstack-export/src/lib/export/assets.js
- packages/contentstack-export/src/lib/export/entries.js
- packages/contentstack-export/src/lib/export/environments.js
- packages/contentstack-export/src/lib/export/extensions.js
- packages/contentstack-export/src/lib/export/global-fields.js
- packages/contentstack-export/src/lib/export/marketplace-apps.js
- packages/contentstack-import/src/app.js
- packages/contentstack-import/src/lib/import/assets.js
- packages/contentstack-import/src/lib/import/extensions.js
- packages/contentstack-import/src/lib/import/global-fields.js
- packages/contentstack-import/src/lib/import/marketplace-apps.js
- Marketplace apps stability action points fix/changes
> Marketplace apps stability

- packages/contentstack-export/src/lib/export/labels.js
- packages/contentstack-import/src/lib/import/labels.js
- Labels stability action points fix/changes
> Labels stability action points fix/changes

- packages/contentstack-export/src/config/default.js
- packages/contentstack-export/src/lib/export/webhooks.js
- packages/contentstack-import/src/lib/import/webhooks.js
- Webhooks stability action points fix/changes
> Webhooks stability

- packages/contentstack-export/src/config/default.js
- packages/contentstack-export/src/lib/export/custom-roles.js
- packages/contentstack-export/src/lib/export/environments.js
- packages/contentstack-export/src/lib/export/extensions.js
- packages/contentstack-export/src/lib/export/global-fields.js
- packages/contentstack-export/src/lib/export/labels.js
- packages/contentstack-export/src/lib/export/webhooks.js
- packages/contentstack-export/src/lib/export/workflows.js
- packages/contentstack-import/src/app.js
- packages/contentstack-import/src/config/default.js
- packages/contentstack-import/src/lib/import/custom-roles.js
- packages/contentstack-import/src/lib/import/environments.js
- packages/contentstack-import/src/lib/import/extensions.js
- packages/contentstack-import/src/lib/import/global-fields.js
- packages/contentstack-import/src/lib/import/labels.js
- packages/contentstack-import/src/lib/import/locales.js
- packages/contentstack-import/src/lib/import/webhooks.js
- packages/contentstack-import/src/lib/import/workflows.js
- Workflows, Locales, custom-roles modules stability action points fix/changes, file utility changes
> workflows, Locales, custom-roles modules stability action points

- packages/contentstack-export/src/lib/export/custom-roles.js
- packages/contentstack-export/src/lib/export/webhooks.js
- packages/contentstack-import/src/lib/import/custom-roles.js
- packages/contentstack-import/src/lib/import/global-fields.js
- packages/contentstack-import/src/lib/util/fs.js
- Overall Export/Import module related fixes
> Export module reference related fixes

- packages/contentstack-export-to-csv/src/util/index.js
> fix(export-to-csv): implemented org users pagination

- packages/contentstack-export-to-csv/src/util/index.js
> Revert "Fix/users pagination"

- package-lock.json
- packages/contentstack-bootstrap/src/bootstrap/interactive.ts
- packages/contentstack-seed/package.json
- packages/contentstack-seed/src/commands/cm/stacks/seed.ts
- packages/contentstack-seed/src/seed/contentstack/client.ts
- packages/contentstack-seed/src/seed/github/client.ts
- packages/contentstack-seed/src/seed/index.ts
- packages/contentstack-seed/src/seed/interactive.ts
- packages/contentstack-seed/tests/interactive.test.ts
- packages/contentstack-utilities/package.json
- Can not read undefined inquirer issue fix/inquirer import issue fix
> Inquirer import issue fix

- packages/contentstack-bootstrap/src/bootstrap/utils.ts
> fix(bootstrap): fixed stencil app issue

- packages/contentstack-export/src/app.js
- packages/contentstack-import/src/app.js
- packages/contentstack-import/src/lib/import/marketplace-apps.js
**CS-32710**
- Marketplace app config issue | Update cmsApiKey with current stack-api key
> Cs 32710 | Update cmsApiKey

- packages/contentstack-export/src/lib/export/marketplace-apps.js
- packages/contentstack-import/src/lib/import/marketplace-apps.js
- Marketplace app encryption key prompt logic change | To obtain the encryption key, only ask the prompt if the configuration exists. 
- On import suggest default marketplace app name logic updated
> To obtain the encryption key, only ask the prompt if the configuration exists.

- package-lock.json
- packages/contentstack-export-to-csv/package.json
- The inquirer-checkbox-plus-prompt package-specific version installed to fix the inquirer interdependency issue (https://github.com/faressoft/inquirer-checkbox-plus-prompt/issues/15)
> inquirer-checkbox-plus-prompt package specific version installed

- package-lock.json
- packages/contentstack-auth/README.md
- packages/contentstack-auth/package.json
- packages/contentstack-bootstrap/README.md
- packages/contentstack-bulk-publish/README.md
- packages/contentstack-clone/README.md
- packages/contentstack-command/package.json
- packages/contentstack-config/README.md
- packages/contentstack-config/package.json
- packages/contentstack-export/README.md
- packages/contentstack-export/package.json
- packages/contentstack-import/README.md
- packages/contentstack-migrate-rte/README.md
- packages/contentstack-migration/README.md
- packages/contentstack-utilities/package.json
- packages/contentstack/README.md
- Mocha version vulnerable issue fix
> Dependency vulnerable fix

- package-lock.json
- packages/contentstack-auth/README.md
- packages/contentstack-auth/package.json
- packages/contentstack-bootstrap/README.md
- packages/contentstack-bootstrap/package.json
- packages/contentstack-bulk-publish/README.md
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-clone/README.md
- packages/contentstack-clone/package.json
- packages/contentstack-command/package.json
- packages/contentstack-config/README.md
- packages/contentstack-config/package.json
- packages/contentstack-export-to-csv/package.json
- packages/contentstack-export/README.md
- packages/contentstack-export/package.json
- packages/contentstack-import/README.md
- packages/contentstack-import/package.json
- packages/contentstack-migrate-rte/README.md
- packages/contentstack-migrate-rte/package.json
- packages/contentstack-migration/README.md
- packages/contentstack-migration/package.json
- packages/contentstack-seed/package.json
- packages/contentstack-utilities/package.json
- packages/contentstack/README.md
- packages/contentstack/package.json
- @oclif/plugin-help dev dependency removed
> @oclif/plugin-help dev dependency removed

- packages/contentstack-import/src/config/default.js
> fix(custom-roles): custom roles ordering fixed

- packages/contentstack-migration/README.md
- packages/contentstack-migration/package.json
> Migration readme fix

- packages/contentstack-seed/src/seed/github/client.ts
- packages/contentstack-seed/src/seed/index.ts
> fix(bootstrap): handled github rate limit error

- packages/contentstack-export/src/lib/export/stack.js
- Export marketplace apps and their configuration is failing - FIX
> Marketplace apps export fix

- packages/contentstack-import/src/lib/import/marketplace-apps.js
- packages/contentstack-utilities/src/http-client/client.ts
- packages/contentstack-utilities/types/http-client/client.d.ts
**Tickets: CS-32684, CS-34614**
- Code clean
- MKT apps OAuth Redirect URL issue fix
- HTTP client type definition correction, new constructor params introduced.
> Marketplace apps: OAuth redirect URL issue fixed

- packages/contentstack-clone/src/lib/util/clone-handler.js
- packages/contentstack-export/src/lib/util/setup-branches.js
- packages/contentstack-import/src/app.js
- Branch API failure/Clone failing issue fixes
> Clone command failing issue fixes

- packages/contentstack-migration/src/commands/cm/stacks/migration.js
> fix: added host

- packages/contentstack-import/src/lib/import/locales.js
> Seed command fails with error - TypeError: Cannot convert undefined or null to object

- package-lock.json
- packages/contentstack-clone/package.json
- packages/contentstack-import/src/app.js
- packages/contentstack-import/src/lib/import/marketplace-apps.js
- packages/contentstack-migration/README.md
- packages/contentstack-seed/package.json
- pnpm-lock.yaml
Issue - CS-35811
Package versions are already updated, no need to update again in this PR.
> Marketplace apps: private app creation fixes

- package-lock.json
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-bulk-publish/src/commands/cm/assets/publish.js
- packages/contentstack-bulk-publish/src/commands/cm/assets/unpublish.js
- packages/contentstack-bulk-publish/src/commands/cm/bulk-publish/cross-publish.js
- packages/contentstack-bulk-publish/src/commands/cm/entries/publish-modified.js
- packages/contentstack-bulk-publish/src/commands/cm/entries/publish-non-localized-fields.js
- packages/contentstack-bulk-publish/src/commands/cm/entries/publish.js
- packages/contentstack-bulk-publish/src/commands/cm/entries/unpublish.js
- packages/contentstack-bulk-publish/src/commands/cm/entries/update-and-publish.js
- packages/contentstack-bulk-publish/src/commands/cm/stacks/unpublish.js
- packages/contentstack-bulk-publish/src/producer/revert.js
- packages/contentstack-bulk-publish/src/services/publish-only-unpublished.js
- packages/contentstack-bulk-publish/src/util/client.js
- packages/contentstack-bulk-publish/src/util/retryfailed.js
- packages/contentstack/package.json
- pnpm-lock.yaml
Ticket no:- CS-31210
version updated
> Bulk Publish | Replace command class SDK object with utility-based SDK object

- package-lock.json
- packages/contentstack-migration/README.md
- packages/contentstack-migration/package.json
- packages/contentstack-migration/src/commands/cm/stacks/migration.js
- packages/contentstack/package.json
- pnpm-lock.yaml
- @contentstack/cli-migration 1.1.2
- @contentstack/cli 1.3.1
> fix: added fix for unformatted hostname

- packages/contentstack-export/src/commands/cm/stacks/export.ts
- packages/contentstack-export/src/interfaces/default-config.ts
- packages/contentstack-export/src/interfaces/export-config.ts
- packages/contentstack-export/src/interfaces/index.ts
- packages/contentstack-export/types/default-config.d.ts
- packages/contentstack-export/types/export-config.d.ts
CS-34617
version - minor version is already updated
> added types

- packages/contentstack-import/src/lib/util/fs.js
- packages/contentstack-import/src/lib/util/lookupReplaceAssets.js
> fix(import): added a fix for too many open files

- .github/workflows/release.yml
> github release update in release workflow

- packages/contentstack-clone/src/lib/util/clone-handler.js
- packages/contentstack-export/package.json
- packages/contentstack-export/src/export/module-exporter.ts
- packages/contentstack-export/types/index.d.ts
- packages/contentstack-import/package.json
- packages/contentstack-import/types/index.d.ts
- packages/contentstack-seed/src/seed/importer.ts
> Rewrite bug fixes

- .talismanrc
- package-lock.json
> refactor: updated package-lock file

- .github/workflows/release.yml
- .talismanrc
- package-lock.json
> Staging : updated lock file

- packages/contentstack-export/src/commands/cm/stacks/export.js
- packages/contentstack-import/src/commands/cm/stacks/import.js
> fix: required isAuthenticated method from utilities

- packages/contentstack-migration/src/commands/cm/stacks/migration.js
> fix(migration): changes for isAuthenticated

- package-lock.json
- packages/contentstack-auth/README.md
- packages/contentstack-bootstrap/README.md
- packages/contentstack-branch/README.md
- packages/contentstack-branch/src/commands/cm/branches/config.ts
- packages/contentstack-branch/src/commands/cm/branches/index.ts
- packages/contentstack-branch/src/utils/index.ts
- packages/contentstack-bulk-publish/README.md
- packages/contentstack-clone/README.md
- packages/contentstack-config/README.md
- packages/contentstack-export/README.md
- packages/contentstack-import/README.md
- packages/contentstack-migrate-rte/README.md
- packages/contentstack-migration/README.md
- packages/contentstack/README.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18nHNqlrFkffU6GyI6vOk4Eli6R8l1PM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=dYFCh8-)
> code review feedback changes

- packages/contentstack-export/src/lib/export/marketplace-apps.js
> fix(marketplace-import): reverted management sdk initialiser in marketplace

- package-lock.json
- packages/contentstack-branch/.gitignore
- packages/contentstack-branch/README.md
- packages/contentstack-branch/src/commands/cm/branches/config.ts
- packages/contentstack-branch/src/commands/cm/branches/index.ts
- packages/contentstack-branch/src/utils/index.ts
- packages/contentstack-config/README.md
- packages/contentstack-config/src/commands/config/get/branch.ts
- packages/contentstack-config/src/commands/config/set/branch.ts
- packages/contentstack/README.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18nHNqlrFkffU6GyI6vOk4Eli6R8l1PM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=dYFCh8-)
> add api key flags

- packages/contentstack-branch/README.md
- packages/contentstack-branch/src/commands/cm/branches/create.ts
- packages/contentstack-branch/src/commands/cm/branches/delete.ts
- packages/contentstack-branch/src/utils/interactive.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX181z1vWltVwtOuAEoFl52tZRef6sV6u8s%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=FroG_id)
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19MDz1UgueD38I3camGdzyV6b9vsuRjr3w%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=jvg3e2z)
> added changes which were left after merge conflict

- packages/contentstack-config/README.md
- packages/contentstack-config/src/commands/config/get/base-branch.ts
- packages/contentstack-config/src/commands/config/remove/base-branch.ts
- packages/contentstack-config/src/commands/config/set/base-branch.ts
- packages/contentstack-config/src/config/remove-config.ts
- packages/contentstack-config/src/utils/interactive.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX181z1vWltVwtOuAEoFl52tZRef6sV6u8s%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=FroG_id)
> added remove config command

- packages/contentstack-import/src/lib/import/marketplace-apps.js
> fix(marketplace-import): fixed minor issue in marketplace

- packages/contentstack/src/help.ts
> fix(cli): hide aliases

- packages/contentstack-branch/messages/index.json
- packages/contentstack-branch/src/utils/delete-branch.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1qwfpUG1ivVKMvmIVpwpF9EjVYTFnJuM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=0NG3xa2)
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX10776U1XblPzt6yKm8Fzw2ZLmLmRWzY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=QEY_dHj)
> added changes requested by QA

- packages/contentstack-branch/README.md
- packages/contentstack-branch/package.json
- packages/contentstack-config/README.md
- packages/contentstack-config/package.json
- packages/contentstack-config/test/unit/commands/region.test.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18nHNqlrFkffU6GyI6vOk4Eli6R8l1PM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=dYFCh8-)
> resolve path errors in region test file

- packages/contentstack-branch/messages/index.json
- packages/contentstack-branch/src/branch/merge-handler.ts
- packages/contentstack-branch/src/commands/cm/branches/create.ts
- packages/contentstack-branch/src/commands/cm/branches/delete.ts
- packages/contentstack-branch/src/commands/cm/branches/diff.ts
- packages/contentstack-branch/src/commands/cm/branches/merge.ts
- packages/contentstack-branch/src/config/index.ts
- packages/contentstack-branch/src/utils/create-branch.ts
- packages/contentstack-branch/src/utils/delete-branch.ts
- packages/contentstack-branch/src/utils/interactive.ts
- packages/contentstack-branch/src/utils/merge-helper.ts
- packages/contentstack-branch/test/unit/commands/cm/branches/merge.test.ts
- packages/contentstack-branch/test/unit/mock/data.ts
- packages/contentstack-branch/test/unit/utils/diff-branch-handler.test.ts
- packages/contentstack-branch/test/unit/utils/interactive.test.ts
- packages/contentstack-branch/test/unit/utils/merge-branch-handler.test.ts
- packages/contentstack-config/src/commands/config/remove/base-branch.ts
- packages/contentstack-config/src/commands/config/set/base-branch.ts
Tickets:- CS-37569
Doc text review
> Delete branch name confirmation

- packages/contentstack-branch/src/config/index.ts
- packages/contentstack-branch/src/utils/merge-helper.ts
- packages/contentstack-branch/test/unit/commands/cm/branches/merge.test.ts
- packages/contentstack-branch/test/unit/mock/data.ts
- packages/contentstack-branch/test/unit/utils/diff-branch-handler.test.ts
- packages/contentstack-branch/test/unit/utils/interactive.test.ts
- packages/contentstack-branch/test/unit/utils/merge-branch-handler.test.ts
Tickets:- CS-37410, CS-37408, CS-37409
> Merge command, helper and handler testcases

- package-lock.json
- packages/contentstack-auth/package.json
- packages/contentstack-utilities/package.json
- pnpm-lock.yaml
> fix: fixed version for open package

- package-lock.json
- packages/contentstack-launch/package.json
- pnpm-lock.yaml
> Missing type dependency added

- packages/contentstack-launch/src/adapters/base-class.ts
- packages/contentstack-launch/src/adapters/file-upload.ts
- packages/contentstack-launch/src/adapters/github.ts
> Package json file check validation removed for static file upload

- packages/contentstack-export/src/lib/export/content-types.js
> fix(export): handled issue with contenttype named schema

- packages/contentstack-launch/src/commands/launch/deployments.ts
- packages/contentstack-launch/src/commands/launch/environments.ts
- packages/contentstack-launch/src/commands/launch/open.ts
> Launch UI test corrections

- packages/contentstack-branch/src/branch/merge-handler.ts
- packages/contentstack-branch/src/commands/cm/branches/merge.ts
- packages/contentstack-branch/src/interfaces/index.ts
- packages/contentstack-branch/src/utils/create-merge-scripts.ts
- packages/contentstack-launch/README.md
- packages/contentstack/README.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1yfhczHtg2LfiNIM29h91EFSQOsTiEdM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=07Kp8Y_)
> add code review feedback changes

- packages/contentstack-branch/src/utils/create-merge-scripts.ts
- packages/contentstack-branch/src/utils/index.ts
- packages/contentstack-branch/test/unit/utils/create-merge-scripts.test.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19LE4TyVyVdiq7dSrgdvs8CXFC8i9dDOE%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=d0APnt-)
> Entry exp tests 

- packages/contentstack-branch/src/commands/cm/branches/create.ts
- packages/contentstack-branch/src/commands/cm/branches/delete.ts
- packages/contentstack-branch/src/commands/cm/branches/diff.ts
- packages/contentstack-branch/src/commands/cm/branches/index.ts
- packages/contentstack-branch/src/config/index.ts
- packages/contentstack-branch/src/interfaces/index.ts
- packages/contentstack-branch/src/utils/branch-diff-utility.ts
- packages/contentstack-branch/src/utils/index.ts
- packages/contentstack-branch/test/unit/commands/cm/branches/create.test.ts
- packages/contentstack-branch/test/unit/commands/cm/branches/delete.test.ts
- packages/contentstack-branch/test/unit/commands/cm/branches/diff.test.ts
- packages/contentstack-branch/test/unit/commands/cm/branches/list.test.ts
- packages/contentstack-branch/test/unit/mock/data.ts
- packages/contentstack-branch/test/unit/utils/diff-branch-handler.test.ts
- packages/contentstack-branch/test/unit/utils/interactive.test.ts
- packages/contentstack-branch/test/unit/utils/merge-branch-handler.test.ts
- packages/contentstack-config/src/commands/config/set/base-branch.ts
> Fix unit testcases, bug & remove short flag

- packages/contentstack-export-to-csv/src/util/index.js
> fix(export-to-csv): added support for pagination in org selection

- packages/contentstack-branches/src/commands/cm/branches/index.ts
- packages/contentstack-branches/src/utils/create-merge-scripts.ts
- packages/contentstack-branches/src/utils/index.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1yfhczHtg2LfiNIM29h91EFSQOsTiEdM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=07Kp8Y_)
> handle errors in branch list

- package-lock.json
- packages/contentstack-utilities/package.json
- packages/contentstack-utilities/src/cli-ux.ts
- packages/contentstack-utilities/src/index.ts
- packages/contentstack-utilities/src/inquirer-table-prompt.ts
- pnpm-lock.yaml
> inquirer-table-prompt package migration

- package-lock.json
- pnpm-lock.yaml
> Lock files updated

- package-lock.json
- packages/contentstack-export/package.json
- pnpm-lock.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19GteoEgh810WUqjttKyRgF7Yr3nqaJ6Q%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=tFPlSXf)
> upgraded packages for snyk issues

- packages/contentstack-launch/package.json
- packages/contentstack-launch/test/unit/adapters/file-upload.test.ts
- packages/contentstack-launch/test/unit/adapters/github.test.ts
- packages/contentstack-launch/test/unit/commands/launch.test.ts
- packages/contentstack-launch/test/unit/commands/log.test.ts
- packages/contentstack-launch/test/unit/mock/index.ts
- packages/contentstack-launch/test/unit/util/log.test.ts
- packages/contentstack-launch/test/unit/util/logs-polling-utilities.test.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1IxFhHZzMLEhYX0eSlcwpWzDhr0J2oM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=PIXGMTb)
> unit tests - github and fileupload adapter

- packages/contentstack-launch/package.json
- packages/contentstack-launch/test/unit/adapters/file-upload.test.ts
- packages/contentstack-launch/test/unit/adapters/github.test.ts
- packages/contentstack-launch/test/unit/commands/launch.test.ts
- packages/contentstack-launch/test/unit/commands/log.test.ts
- packages/contentstack-launch/test/unit/mock/index.ts
- packages/contentstack-launch/test/unit/util/log.test.ts
- packages/contentstack-launch/test/unit/util/logs-polling-utilities.test.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1IxFhHZzMLEhYX0eSlcwpWzDhr0J2oM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=PIXGMTb)
> Launch unit test

- packages/contentstack-launch/src/commands/launch/base-command.ts
> fix(launch): handled logged out event

- packages/contentstack-export/README.md
- packages/contentstack-export/example_config/auth_config.json
- packages/contentstack-export/example_config/management_config.json
- packages/contentstack-import/README.md
- packages/contentstack-import/example_config/auth_config.json
- packages/contentstack-import/example_config/management_config.json
> Update example config for contentstack export & import plugin

- packages/contentstack-utilities/src/auth-handler.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18j40sQ1N1iRMfV5PZVwqzxgarY7Kbfyw%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=sFnLM2R)
Ticket No.: CS-39028
No Version bump done
> Oauth screen UI update

- packages/contentstack-import/src/lib/import/custom-roles.js
- packages/contentstack-import/src/lib/import/entries.js
> Display label fix

- package-lock.json
- packages/contentstack-clone/package.json
- packages/contentstack-clone/src/lib/util/clone-handler.js
- pnpm-lock.yaml
> fix(clone): fixed undo command for import flow

- packages/contentstack-import/src/lib/import/entries.js
Ticket no:- https://contentstack.atlassian.net/browse/CS-39527
Version already bump
> Entries publish error -> Please provide valid parameter for environments

- packages/contentstack-branches/src/utils/branch-diff-utility.ts
Ticket:- https://contentstack.atlassian.net/browse/CS-39275
> Display changed content type properties in detail text mode

- packages/contentstack-auth/messages/index.json
- packages/contentstack-auth/src/commands/auth/tokens/add.ts
- packages/contentstack-auth/src/commands/auth/tokens/index.ts
- packages/contentstack-auth/src/utils/tokens-validation.ts
- added branch flag
- login issue fixed for both management and delivery token addition
- prompt to enter branch name removed for delivery token, only can add with --branch flag
> CS-39152 delivery token branch flag and login issue fixed 

- package-lock.json
- packages/contentstack-auth/README.md
- packages/contentstack-auth/package.json
- packages/contentstack-bootstrap/README.md
- packages/contentstack-bootstrap/package.json
- packages/contentstack-branches/README.md
- packages/contentstack-branches/package.json
- packages/contentstack-bulk-publish/README.md
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-clone/README.md
- packages/contentstack-clone/package.json
- packages/contentstack-config/README.md
- packages/contentstack-config/package.json
- packages/contentstack-export-to-csv/package.json
- packages/contentstack-export/README.md
- packages/contentstack-export/package.json
- packages/contentstack-import/README.md
- packages/contentstack-import/src/import/modules-js/entries.js
- packages/contentstack-launch/README.md
- packages/contentstack-launch/oclif.manifest.json
- packages/contentstack-launch/package.json
- packages/contentstack-migrate-rte/README.md
- packages/contentstack-migrate-rte/package.json
- packages/contentstack-migration/README.md
- packages/contentstack-migration/package.json
- packages/contentstack-seed/package.json
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
> Merge stage to development

- packages/contentstack-import/src/import/modules-js/entries.js
- corrected `formatError` function call
> fix: corrected function call

- packages/contentstack-export/src/config/index.ts
- packages/contentstack-export/src/export/module-exporter.ts
- packages/contentstack-export/src/export/modules/environments.ts
- packages/contentstack-export/src/export/modules/extensions.ts
- packages/contentstack-export/src/export/modules/marketplace-apps.ts
- packages/contentstack-export/src/types/index.ts
- packages/contentstack-export/src/utils/marketplace-app-helper.ts
- packages/contentstack-export/test/integration/environments.test.js
- packages/contentstack-export/test/integration/extensions.test.js
- packages/contentstack-export/test/integration/marketplace-apps.test.js
- packages/contentstack-export/test/integration/utils/helper.js
- packages/contentstack-import/src/config/index.ts
- packages/contentstack-import/src/import/modules/base-class.ts
- packages/contentstack-import/src/import/modules/environments.ts
- packages/contentstack-import/src/import/modules/extensions.ts
- packages/contentstack-import/src/import/modules/marketplace-apps.ts
- packages/contentstack-import/src/types/index.ts
- packages/contentstack-import/src/utils/extension-helper.ts
- packages/contentstack-import/src/utils/marketplace-app-helper.ts
> Environments export & import rewrite

- packages/contentstack-seed/README.md
- packages/contentstack-seed/src/commands/cm/stacks/seed.ts
- packages/contentstack-seed/src/seed/contentstack/client.ts
- packages/contentstack-seed/src/seed/importer.ts
- packages/contentstack-seed/src/seed/index.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18FHsUoBLAz4btL8pxn0KQtjngVuJGkEnM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=ALnOdzX)
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18F8KScm0cM5div2FNVjEryQjG1aRPDyY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=ierqObz)
> CS-38607 - merge seed into bootstrap

- packages/contentstack-export/src/config/index.ts
- packages/contentstack-export/src/export/modules/labels.ts
- packages/contentstack-export/src/types/index.ts
- packages/contentstack-import/src/config/index.ts
- packages/contentstack-import/src/import/modules/base-class.ts
- packages/contentstack-import/src/import/modules/labels.ts
- packages/contentstack-import/src/types/index.ts
> Label export & import rewrite

- packages/contentstack-export/src/config/index.ts
- packages/contentstack-export/src/export/modules/environments.ts
- packages/contentstack-export/src/export/modules/extensions.ts
- packages/contentstack-export/src/export/modules/labels.ts
- packages/contentstack-export/src/export/modules/webhooks.ts
- packages/contentstack-export/src/types/index.ts
- packages/contentstack-export/test/integration/webhooks.test.js
- packages/contentstack-import/src/config/index.ts
- packages/contentstack-import/src/import/modules/base-class.ts
- packages/contentstack-import/src/import/modules/environments.ts
- packages/contentstack-import/src/import/modules/extensions.ts
- packages/contentstack-import/src/import/modules/labels.ts
- packages/contentstack-import/src/import/modules/marketplace-apps.ts
- packages/contentstack-import/src/import/modules/webhooks.ts
- packages/contentstack-import/src/types/index.ts
> Webhook export & import rewrite and pagination support in webhook, extension & environment

- packages/contentstack-export/example_config/management_config.json
- packages/contentstack-export/src/config/index.ts
- packages/contentstack-import/example_config/auth_config.json
- packages/contentstack-import/src/config/index.ts
- packages/contentstack-import/src/types/default-config.ts
- packages/contentstack-import/src/utils/backup-handler.ts
> Fix backup-dir flag in import command

- packages/contentstack-export/package.json
- packages/contentstack-export/src/export/modules/locales.ts
- packages/contentstack-export/test/integration/custom-roles.test.js
- packages/contentstack-export/test/integration/global-fields.test.js
- packages/contentstack-export/test/integration/locales.test.js
- packages/contentstack-export/test/integration/marketplace-apps.test.js
- packages/contentstack-export/test/integration/webhooks.test.js
- packages/contentstack-export/test/integration/workflows.test.js
> fix: export plugin test cases

- packages/contentstack-export/src/export/modules/stack.ts
- packages/contentstack-export/src/export/modules/webhooks.ts
- packages/contentstack-export/src/export/modules/workflows.ts
- packages/contentstack-import/src/utils/import-config-handler.ts
> Fix: stack module rewrite mg token issue

- .github/workflows/release.yml
- added a fix for failing release workflow
> fix: added prepack sections for export and import commands

- packages/contentstack-import/src/import/modules-js/workflows.js
- packages/contentstack-import/src/import/modules/base-class.ts
- packages/contentstack-import/src/import/modules/workflows.ts
> Fix: Workflow stage UID remains same after export and import of stack

- packages/contentstack-import/src/import/modules-js/entries.js
- packages/contentstack-import/src/utils/entries-helper.ts
> fix: added empty children condition to the multiple case

- packages/contentstack-export/src/commands/cm/stacks/export.ts
- packages/contentstack-import/src/commands/cm/stacks/import.ts
- packages/contentstack-import/src/utils/entries-helper.ts
- packages/contentstack-import/src/utils/logger.ts
> Import & Export Bug fixes & Enhancements

- packages/contentstack-branches/src/branch/merge-handler.ts
- packages/contentstack-branches/src/utils/asset-folder-create-script.ts
- packages/contentstack-branches/src/utils/create-merge-scripts.ts
- packages/contentstack-branches/src/utils/entry-create-script.ts
- packages/contentstack-branches/src/utils/entry-create-update-script.ts
- packages/contentstack-branches/src/utils/entry-update-script.ts
- packages/contentstack-migration/src/commands/cm/stacks/migration.js
> feat: Entry Exp | Generate assets migration scripts

- package-lock.json
- packages/contentstack-import/package.json
- packages/contentstack-import/src/commands/cm/stacks/import.ts
- packages/contentstack-import/src/config/index.ts
- packages/contentstack-import/src/import/module-importer.ts
- packages/contentstack-import/src/import/modules/base-class.ts
- packages/contentstack-import/src/import/modules/custom-roles.ts
- packages/contentstack-import/src/import/modules/entries.ts
- packages/contentstack-import/src/import/modules/labels.ts
- packages/contentstack-import/src/import/modules/workflows.ts
- packages/contentstack-utilities/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
> Enable environment new structure

- packages/contentstack-export/src/export/modules/workflows.ts
> Export - Workflows exporting step does not stop in Azure-NA region

- packages/contentstack-import/src/import/modules-js/workflows.js
- packages/contentstack-import/src/import/modules/workflows.ts
> Fix: Workflow update API issue fix

- package-lock.json
- packages/contentstack-branches/package.json
- packages/contentstack-branches/src/utils/merge-helper.ts
- packages/contentstack/package.json
- pnpm-lock.yaml
> Bugfix/CS-40899 - changed the sequence of prompts for base branch and compare branch

- packages/contentstack-export/src/export/modules/custom-roles.ts
- packages/contentstack-export/src/export/modules/environments.ts
- packages/contentstack-export/src/export/modules/extensions.ts
- packages/contentstack-export/src/export/modules/labels.ts
- packages/contentstack-export/src/export/modules/marketplace-apps.ts
- packages/contentstack-export/src/export/modules/stack.ts
- packages/contentstack-export/src/export/modules/webhooks.ts
- packages/contentstack-export/src/export/modules/workflows.ts
- packages/contentstack-import/src/import/modules/custom-roles.ts
- packages/contentstack-import/src/import/modules/environments.ts
- packages/contentstack-import/src/import/modules/extensions.ts
- packages/contentstack-import/src/import/modules/labels.ts
- packages/contentstack-import/src/import/modules/marketplace-apps.ts
- packages/contentstack-import/src/import/modules/webhooks.ts
- packages/contentstack-import/src/import/modules/workflows.ts
> Export | Import | Remove import config 

- packages/contentstack-utilities/src/config-handler.ts
> Feat: Enable users to generate a CLI configuration file in their chosen directory path.

- packages/contentstack-import/src/utils/asset-helper.ts
> corrected type path

- package-lock.json
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
> Version bumped

- packages/contentstack-import/package.json
- packages/contentstack-import/src/import/modules/entries.ts
- packages/contentstack/package.json
CS-41724
Import version bumped to 1.9.2
> fixed manadatory removal of CT

- packages/contentstack-export/package.json
- packages/contentstack-export/src/commands/cm/stacks/export.ts
- packages/contentstack-export/src/export/module-exporter.ts
- packages/contentstack-export/src/utils/common-helper.ts
- packages/contentstack/package.json
CS-41661
export version bumped to 1.9.2
> fix export info in all branches

- packages/contentstack-export/package.json
- packages/contentstack-import/package.json
- corrected code for analytics
- no version bumped, as no code changes
> fix: corrected code for analytics

- package-lock.json
- packages/contentstack-export-to-csv/src/util/config.js
- packages/contentstack-export-to-csv/src/util/index.js
- packages/contentstack-export/src/config/index.ts
- packages/contentstack-export/src/export/modules/taxonomies.ts
- packages/contentstack-import/package.json
- packages/contentstack-import/src/import/modules/content-types.ts
- packages/contentstack-import/src/import/modules/entries.ts
- packages/contentstack-import/src/utils/logger.ts
- packages/contentstack-import/src/utils/taxonomies-helper.ts
- packages/contentstack-utilities/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
> Taxonomy | Internal demo suggestions and sdk issue

- packages/contentstack-export-to-csv/src/commands/cm/export-to-csv.js
> fix: Nullish coalescing operator in export-to-csv plugin

- packages/contentstack-export-to-csv/src/util/index.js
- packages/contentstack-export-to-csv/test/mock-data/common.mock.json
- packages/contentstack-export-to-csv/test/unit/commands/export-to-csv.test.js
Version Bump: no
Removed the jest test cases
> Feat/CS-42000 -  Added Unit test cases for teams support in export-to-csv

- packages/contentstack-export-to-csv/src/util/config.js
- packages/contentstack-migration/examples/taxonomies/import-taxonomies.js
> feat: migration script to read a CSV file and import taxonomy

- packages/contentstack-export-to-csv/src/commands/cm/export-to-csv.js
- packages/contentstack-export-to-csv/src/util/index.js
- packages/contentstack-migration/examples/taxonomies/import-taxonomies.js
- packages/contentstack-migration/examples/taxonomies/test_taxonomies.csv
> Add delimiter support in "Export-to-CSV plugin" and taxonomies import utility

- .gitignore
- package-lock.json
- packages/contentstack-audit/README.md
- packages/contentstack-audit/package.json
- packages/contentstack-audit/src/audit-base-command.ts
- packages/contentstack-audit/src/base-command.ts
- packages/contentstack-audit/src/commands/cm/stacks/audit/fix.ts
- packages/contentstack-audit/src/commands/cm/stacks/audit/index.ts
- packages/contentstack-audit/src/config/index.ts
- packages/contentstack-audit/src/messages/index.ts
- packages/contentstack-audit/src/modules/content-types.ts
- packages/contentstack-audit/src/modules/entries.ts
- packages/contentstack-audit/src/types/common.ts
- packages/contentstack-audit/src/types/content-types.ts
- packages/contentstack-audit/src/types/index.ts
- packages/contentstack-audit/src/util/flags.ts
- packages/contentstack-audit/src/util/index.ts
- packages/contentstack-audit/test/unit/audit-base-command.test.ts
- packages/contentstack-audit/test/unit/mock/contents/entries/page_1/en-us/e7f6e3cc-64ca-4226-afb3-7794242ae5f5-entries.json
- packages/contentstack-audit/test/unit/mock/contents/locales/master-locale.json
- packages/contentstack-audit/test/unit/mock/mock.json
- packages/contentstack-audit/test/unit/modules/content-types.test.ts
- packages/contentstack-audit/test/unit/modules/entries.test.ts
- packages/contentstack-audit/test/unit/util/flags.test.ts
- packages/contentstack-dev-dependencies/package.json
- packages/contentstack/README.md
- pnpm-lock.yaml
> Feat: Add missing global fields schema in to content type

- packages/contentstack-audit/README.md
- packages/contentstack-audit/src/messages/index.ts
- packages/contentstack-audit/src/util/flags.ts
- packages/contentstack/README.md
> Doc: Updated doc reviewed UI texts

- packages/contentstack-export/package.json
- packages/contentstack-export/src/export/module-exporter.ts
- packages/contentstack/package.json
CS-42526
Version bump: export 1.9.4
> fixed branch exports

- package-lock.json
- packages/contentstack-export/README.md
- packages/contentstack-export/package.json
- packages/contentstack-export/src/export/module-exporter.ts
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
> branch export fix

- package-lock.json
- packages/contentstack-utilities/package.json
- packages/contentstack-utilities/src/contentstack-management-sdk.ts
- packages/contentstack-utilities/src/contentstack-marketplace-sdk.ts
- packages/contentstack-utilities/src/index.ts
> feat: New marketplace sdk adapter added in utility [CS-42859]

- packages/contentstack-import/src/import/modules-js/workflows.js
- packages/contentstack-import/src/import/modules/workflows.ts
> fix: workflow update failure issue

- packages/contentstack-export/src/export/modules/marketplace-apps.ts
NOTE: No version bum required.
> Fix: Missing marketplace apps configuration export functionality added

- packages/contentstack-clone/README.md
- packages/contentstack-config/README.md
- packages/contentstack-config/messages/index.json
- packages/contentstack-config/src/commands/config/get/early-access-header.ts
- packages/contentstack-config/src/commands/config/remove/early-access-header.ts
- packages/contentstack-config/src/commands/config/set/early-access-header.ts
- packages/contentstack-import/README.md
- packages/contentstack/README.md
> early access header ui text updates

- package-lock.json
- packages/contentstack-clone/package.json
- packages/contentstack-import/package.json
- packages/contentstack-import/src/config/index.ts
- packages/contentstack-import/src/utils/asset-helper.ts
- packages/contentstack-seed/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack/cli-cm-import: 1.13.0 -> 1.13.1
> CS-43269-gcp changes in import

- LICENSE
- README.md
> fix: updated license & readme file

- .github/workflows/release.yml
> fix: publish audit before import plugin

- .github/workflows/release.yml
- LICENSE
- README.md
- packages/contentstack-audit/LICENSE
- packages/contentstack-auth/LICENSE
- packages/contentstack-bootstrap/LICENSE
- packages/contentstack-branches/LICENSE
- packages/contentstack-bulk-publish/LICENSE
- packages/contentstack-clone/LICENSE
- packages/contentstack-clone/README.md
- packages/contentstack-command/LICENSE
- packages/contentstack-config/LICENSE
- packages/contentstack-config/README.md
- packages/contentstack-config/messages/index.json
- packages/contentstack-config/src/commands/config/get/early-access-header.ts
- packages/contentstack-config/src/commands/config/remove/early-access-header.ts
- packages/contentstack-config/src/commands/config/set/early-access-header.ts
- packages/contentstack-dev-dependencies/LICENSE
- packages/contentstack-export-to-csv/LICENSE
- packages/contentstack-export/LICENSE
- packages/contentstack-import/LICENSE
- packages/contentstack-import/README.md
- packages/contentstack-launch/LICENSE
- packages/contentstack-migrate-rte/LICENSE
- packages/contentstack-migration/LICENSE
- packages/contentstack-seed/LICENSE
- packages/contentstack-utilities/LICENSE
- packages/contentstack/LICENSE
- packages/contentstack/README.md
> Merge staging to development

- package-lock.json
- packages/contentstack-branches/README.md
- packages/contentstack-branches/package.json
- packages/contentstack-branches/src/branch/merge-handler.ts
- packages/contentstack-branches/src/utils/create-merge-scripts.ts
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
> Fix entry migration windows issue

- package-lock.json
- packages/contentstack-audit/package.json
- packages/contentstack-audit/src/commands/cm/stacks/audit/index.ts
- packages/contentstack-audit/src/config/index.ts
- packages/contentstack-audit/src/modules/content-types.ts
- packages/contentstack-bulk-publish/README.md
- packages/contentstack-import/package.json
- packages/contentstack-import/src/import/module-importer.ts
- packages/contentstack-seed/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
> Fix: Import flow breaks when there is a taxonomy field in the schema [CS-43552]

- package-lock.json
- packages/contentstack-audit/README.md
- packages/contentstack-audit/package.json
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
@contentstack/cli-audit 1.3.3 -> 1.3.4
> Audit version bump

- packages/contentstack-bootstrap/src/bootstrap/utils.ts
- packages/contentstack-bootstrap/test/utils.test.js
> CS-43652-fixed the test cases and modified the env created for angular, stencil and nuxt

- package-lock.json
- packages/contentstack-launch/README.md
- packages/contentstack-launch/package.json
- packages/contentstack-launch/src/graphql/mutation.ts
- packages/contentstack-launch/src/graphql/queries.ts
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
> fix: Project query and mutation update

- package-lock.json
- packages/contentstack-branches/package.json
- packages/contentstack-config/package.json
- packages/contentstack-config/src/commands/config/set/region.ts
- packages/contentstack-config/src/utils/interactive.ts
- packages/contentstack-export/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack/cli-config: 1.6.0 -> 1.6.1
> CS-43728-added gcp-na in options to select region and as args. Version bump

- package-lock.json
- packages/contentstack-branches/package.json
- packages/contentstack-clone/package.json
- packages/contentstack-config/package.json
- packages/contentstack-config/src/commands/config/set/region.ts
- packages/contentstack-config/src/utils/interactive.ts
- packages/contentstack-export/package.json
- packages/contentstack-import/package.json
- packages/contentstack-import/src/commands/cm/stacks/import.ts
- packages/contentstack-import/src/utils/import-config-handler.ts
- packages/contentstack-seed/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack: 1.13.0 -> 1.13.1
@contentstack/cli-cm-import: 1.13.2 -> 1.13.3
@contentstack/cli-config: 1.6.0 -> 1.6.1
> Release/CS-43721-Adding the GCP changes

- package-lock.json
- packages/contentstack-export/src/export/modules/taxonomies.ts
- packages/contentstack-import/README.md
- packages/contentstack-import/package.json
- packages/contentstack-import/src/config/index.ts
- packages/contentstack-import/src/import/modules/base-class.ts
- packages/contentstack-import/src/import/modules/taxonomies.ts
- packages/contentstack-import/src/types/default-config.ts
- packages/contentstack-import/src/types/index.ts
- packages/contentstack-import/src/utils/taxonomies-helper.ts
- packages/contentstack/package.json
- pnpm-lock.yaml
> feat: Replaced taxonomy & terms create api with taxonomy import

- package-lock.json
- packages/contentstack-import/package.json
- packages/contentstack-utilities/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
> Updated management sdk version from 1.15.2 to 1.15.3

- package-lock.json
- packages/contentstack-bootstrap/package.json
- packages/contentstack-bootstrap/src/bootstrap/utils.ts
- packages/contentstack-bootstrap/src/config.ts
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack/cli-bootstrap: 1.8.0 -> 1.9.0
> CS-43755- nuxt3 added, deperaction warning for nuxt, env file creation for angular app and version bump

- package-lock.json
- packages/contentstack-clone/package.json
- packages/contentstack-clone/src/commands/cm/stacks/clone.js
- pnpm-lock.yaml
> Updated rimraf version from 3.0.2 to 5.0.5

- package-lock.json
- packages/contentstack-audit/README.md
- packages/contentstack-audit/package.json
- packages/contentstack-auth/package.json
- packages/contentstack-bootstrap/README.md
- packages/contentstack-bootstrap/package.json
- packages/contentstack-branches/package.json
- packages/contentstack-bulk-publish/README.md
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-clone/package.json
- packages/contentstack-command/package.json
- packages/contentstack-config/package.json
- packages/contentstack-export-to-csv/package.json
- packages/contentstack-export/README.md
- packages/contentstack-export/package.json
- packages/contentstack-import/package.json
- packages/contentstack-launch/package.json
- packages/contentstack-migrate-rte/package.json
- packages/contentstack-migration/package.json
- packages/contentstack-seed/package.json
- packages/contentstack-utilities/package.json
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
@contentstack/cli 1.14.1 -> 1.15.0
fix @contentstack/cli-utilities 1.15.3 -> 1.15.2
> Sprint52 version bump

- packages/contentstack-migration/src/utils/error-helper.js
> fix: handle module not found error in migration error helper

- packages/contentstack-audit/src/audit-base-command.ts
- packages/contentstack-audit/src/messages/index.ts
- packages/contentstack-audit/src/modules/entries.ts
- packages/contentstack-audit/src/types/utils.ts
- packages/contentstack-audit/src/util/log.ts
- packages/contentstack-audit/test/unit/util/log.test.ts
> Fix: Audit fix log sequence issue fix

- packages/contentstack-audit/src/messages/index.ts
- packages/contentstack-bulk-publish/src/consumer/publish.js
- packages/contentstack-import/src/utils/asset-helper.ts
- packages/contentstack-import/src/utils/common-helper.ts
- packages/contentstack-import/src/utils/entries-helper.ts
- packages/contentstack-utilities/src/helpers.ts
> fix: semgrep reported issues

- package-lock.json
- packages/contentstack-audit/package.json
- packages/contentstack-audit/src/audit-base-command.ts
- packages/contentstack-audit/src/config/index.ts
- packages/contentstack-audit/src/messages/index.ts
- packages/contentstack-audit/src/modules/entries.ts
- packages/contentstack-audit/src/types/utils.ts
- packages/contentstack-audit/src/util/log.ts
- packages/contentstack-audit/test/unit/util/log.test.ts
- packages/contentstack-clone/package.json
- packages/contentstack-import/package.json
- packages/contentstack-import/src/config/index.ts
- packages/contentstack-import/src/import/module-importer.ts
- packages/contentstack-import/src/types/default-config.ts
- packages/contentstack-seed/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
> Hotfix: import global field are missing fix

- package-lock.json
> Package lock file updated

- package-lock.json
- packages/contentstack-launch/README.md
- packages/contentstack-launch/package.json
- packages/contentstack-launch/src/util/cloud-function/cloud-functions.ts
- packages/contentstack/package.json
- pnpm-lock.yaml
> fix: handled request.body undefined issue in launch plugin

- package-lock.json
- packages/contentstack-bootstrap/package.json
- packages/contentstack-clone/package.json
- packages/contentstack-import/package.json
- packages/contentstack-import/src/import/modules/entries.ts
- packages/contentstack-import/src/utils/content-type-helper.ts
- packages/contentstack-import/src/utils/entries-helper.ts
- packages/contentstack-seed/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack/cli : 1.16.0 -> 1.17.0
@contentstack/cli-cm-import: 1.14.2 -> 1.15.0
@contentstack/cli-cm-clone: 1.10.2 -> 1.10.3
@contentstack/cli-cm-seed: 1.7.2 -> 1.7.3
> CS-43630 - Handling the embedded entries cretion in RTE, version bump

- package-lock.json
- packages/contentstack-clone/package.json
- packages/contentstack-import/package.json
- packages/contentstack-import/src/utils/asset-helper.ts
- packages/contentstack-seed/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack: 1.16.0 -> 1.16.1
@contentstack/cli-cm-import: 1.14.2 -> 1.14.3
> Fix/CS-44467 -  Fixed broken Embedded assets links in JSON rte after import

- packages/contentstack-import/src/utils/entries-helper.ts
> Bugfix/CS-44546- Removed the return statement when checking for references 

- packages/contentstack-audit/src/audit-base-command.ts
- packages/contentstack-audit/src/modules/extensions.ts
- packages/contentstack-audit/src/modules/workflows.ts
- packages/contentstack-migration/src/utils/error-helper.js
Removed the request body from error in the migration loggers
> Bugfix/CS-44565 - Resolved issue when content not overwritten in import backup folder when using audit fix with import 

- package-lock.json
- packages/contentstack-migration/examples/change-master-locale/02-change-master-locale-new-file-structure.js
- packages/contentstack-migration/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack/cli-migration: 1.5.2 -> 1.5.3
> CS-44196 - Modified the change master locale script to adapt to new file structure and created new script

- package-lock.json
- packages/contentstack-clone/package.json
- packages/contentstack-import/package.json
- packages/contentstack-import/src/import/modules/marketplace-apps.ts
- packages/contentstack-import/src/types/import-config.ts
- packages/contentstack-import/src/utils/marketplace-app-helper.ts
- packages/contentstack-seed/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
The Private apps creation on marketplace is skipped and Installation on stack also.
version bump:
@contentstack/cli-cm-import: 1.15.0 -> 1.15.1
@contentstack/cli: 1.17.1 -> 1.17.2
> CS-44299 - fix: Resolved the issue of private apps re-creation after selecting no in the prompt

- package-lock.json
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-bulk-publish/src/producer/cross-publish.js
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack/cli-cm-bulk-publish: 1.4.3 -> 1.4.4
> CS - 44112 - fixed the bulk publishing of all entries when single entry is passed and version bump

- package-lock.json
- packages/contentstack-audit/package.json
- packages/contentstack-audit/src/modules/workflows.ts
- packages/contentstack-import/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack/cli-audit: 1.5.2 -> 1.5.3
> CS- 44642 - handled the case when no branches are passed to check and version bump

- package-lock.json
- packages/contentstack-import/src/utils/marketplace-app-helper.ts
version bump:
Already in development
> CS - 44776 - fix: Handled the case when yes flag is passed for skipping the marketplace prompts

- package-lock.json
- packages/contentstack-migration/examples/05-Update-reference-entry-from-mapper.js
- packages/contentstack-migration/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack/cli: 1.17.3 -> 1.17.4
@contentstack/cli-migration: 1.5.3 -> 1.5.4
> CS - 44747 - added new script for update of references used in entries

- package-lock.json
- packages/contentstack-clone/package.json
- packages/contentstack-import/README.md
- packages/contentstack-import/package.json
- packages/contentstack-import/src/import/modules/assets.ts
- packages/contentstack-seed/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
@contentstack/cli-cm-import 1.15.2 -> 1.15.3
@contentstack/cli 1.17.4 -> 1.17.5
> fix: resolved the asset publish issue caused by the multiple languages

- package-lock.json
- packages/contentstack-clone/package.json
- packages/contentstack-import/package.json
- packages/contentstack-import/src/import/modules/content-types.ts
- packages/contentstack-import/src/utils/marketplace-app-helper.ts
- packages/contentstack-seed/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
Added condition to show extension updated message successfully, in marketplace for private app creation handled the prompt when user want to create the apps.
Version bump:
@contentstack/cli-cm-import: 1.15.3 -> 1.15.4
> DX - 54 - Extension update message and Marketplace private apps Creation

- package-lock.json
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-bulk-publish/src/consumer/publish.js
- packages/contentstack/package.json
- pnpm-lock.yaml
changed remove publish_details function and changed the logs for both entries and assets publishing and version bump
version bump:
@contentstack/cli-cm-bulk-publish: 1.4.5 -> 1.4.6
> DX - 92 - Modified the logs for bulk publish

- package-lock.json
- packages/contentstack-audit/package.json
- packages/contentstack-auth/package.json
- packages/contentstack-bootstrap/package.json
- packages/contentstack-branches/package.json
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-clone/package.json
- packages/contentstack-command/package.json
- packages/contentstack-config/package.json
- packages/contentstack-export-to-csv/package.json
- packages/contentstack-export/package.json
- packages/contentstack-import/package.json
- packages/contentstack-launch/package.json
- packages/contentstack-migrate-rte/package.json
- packages/contentstack-migration/package.json
- packages/contentstack-seed/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack/cli-command: 1.2.17 -> 1.2.18
> cli-command version bump

- package-lock.json
- packages/contentstack-branches/src/utils/asset-folder-create-script.ts
version bump:
Already Done in development
> DX - 525 - fixed the generating tree structure for the assets during branches merge

- package-lock.json
- packages/contentstack-bootstrap/package.json
- packages/contentstack-bootstrap/src/config.ts
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
Reverted the version bump of bootstrap command
Removed the compass app option
> fix: Reverted bootstrap changes

- package-lock.json
- packages/contentstack-audit/package.json
- packages/contentstack-auth/package.json
- packages/contentstack-bootstrap/package.json
- packages/contentstack-branches/package.json
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-clone/package.json
- packages/contentstack-command/package.json
- packages/contentstack-config/package.json
- packages/contentstack-export-to-csv/package.json
- packages/contentstack-export/package.json
- packages/contentstack-import/package.json
- packages/contentstack-launch/package.json
- packages/contentstack-migrate-rte/package.json
- packages/contentstack-migration/package.json
- packages/contentstack-seed/package.json
- packages/contentstack-utilities/package.json
- packages/contentstack/package.json
> dx | 809 marketplace version upgrade

- package-lock.json
- packages/contentstack-audit/package.json
- packages/contentstack-auth/package.json
- packages/contentstack-bootstrap/package.json
- packages/contentstack-branches/package.json
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-clone/package.json
- packages/contentstack-command/package.json
- packages/contentstack-config/package.json
- packages/contentstack-export-to-csv/package.json
- packages/contentstack-export/package.json
- packages/contentstack-import/package.json
- packages/contentstack-launch/package.json
- packages/contentstack-migrate-rte/package.json
- packages/contentstack-migration/package.json
- packages/contentstack-seed/package.json
- packages/contentstack-utilities/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
upgraded cli-utilities package to 1.6.3
> upgraded cli-utilities package to 1.6.3

- package-lock.json
- packages/contentstack-audit/package.json
- packages/contentstack-auth/package.json
- packages/contentstack-bootstrap/package.json
- packages/contentstack-branches/package.json
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-clone/package.json
- packages/contentstack-command/package.json
- packages/contentstack-config/package.json
- packages/contentstack-export-to-csv/package.json
- packages/contentstack-export/package.json
- packages/contentstack-import/package.json
- packages/contentstack-launch/package.json
- packages/contentstack-migrate-rte/package.json
- packages/contentstack-migration/package.json
- packages/contentstack-seed/package.json
- packages/contentstack-utilities/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
upgrade cli-utilities to 1.6.3
> upgrade cli-utilities to 1.6.3

- package-lock.json
- packages/contentstack-dev-dependencies/.snyk
- packages/contentstack-launch/README.md
- packages/contentstack-launch/package.json
- packages/contentstack-launch/src/config/index.ts
- packages/contentstack/package.json
- pnpm-lock.yaml
> Update the config file to support other frameworks similar like UI

- packages/contentstack-launch/src/adapters/base-class.ts
> fix: org uid validation when provided thru flag

- package-lock.json
- packages/contentstack-audit/README.md
- packages/contentstack-launch/README.md
- packages/contentstack-launch/package.json
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
cli-launch: 1.0.20 -> 1.0.19
> fixed launch version

- package-lock.json
- packages/contentstack-migration/examples/06-update-environment-sample-config.json
- packages/contentstack-migration/examples/06-update-environment.js
- packages/contentstack-migration/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump:
@contentstack/cli-migration: 1.6.0 -> 1.6.1
> DX - 996 - Added script to update the enviornments and version bump

- package-lock.json
- packages/contentstack-launch/README.md
- packages/contentstack-launch/package.json
- packages/contentstack-launch/src/adapters/file-upload.ts
- packages/contentstack-launch/src/base-command.ts
- packages/contentstack-launch/src/config/index.ts
- packages/contentstack-launch/src/graphql/mutation.ts
- packages/contentstack-launch/src/util/common-utility.ts
- packages/contentstack-launch/src/util/logs-polling-utilities.ts
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
@contentstack/cli-launch 1.1.0 -> 1.2.0
@contentstack/cli 1.22.0 -> 1.23.0
> feat: enabled azure support in launch plugin

- packages/contentstack-import/src/utils/import-config-handler.ts
> fix: error in branch disabled org

- package-lock.json
- packages/contentstack-bulk-publish/README.md
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-bulk-publish/src/producer/publish-assets.js
- packages/contentstack-bulk-publish/src/producer/publish-entries.js
- packages/contentstack-bulk-publish/src/util/client.js
- packages/contentstack-bulk-publish/src/util/common-utility.js
- packages/contentstack/package.json
- pnpm-lock.yaml
@contentstack/cli-cm-bulk-publish 1.4.8 -> 1.5.0
> feat: added rate limit support in entries & assets bulk publish

- packages/contentstack-audit/README.md
- packages/contentstack-config/README.md
- packages/contentstack/README.md
- packages/contentstack/package.json
- packages/contentstack/src/hooks/prerun/default-rate-limit-check.ts
> feat: set default rate limit using hook

- packages/contentstack-config/src/commands/config/set/rate-limit.ts
- packages/contentstack-config/src/interfaces/index.ts
- packages/contentstack-config/src/utils/rate-limit-handler.ts
- passing host in config and get limit value from organization
> dx | 1472 set rate limit org issue

- packages/contentstack-config/package.json
added abbreviation for config rate limits: set, get and remove
> dx | 1444 | abbreviation for config rate limits

- packages/contentstack-variants/src/import/experiences.ts
> fix: Path Traversal via Path Join/Resolve

- packages/contentstack-variants/src/utils/error-helper.ts
> fix: duplicate project error issue

- package-lock.json
- packages/contentstack-config/README.md
- packages/contentstack-config/package.json
> Release config

- packages/contentstack-export/src/export/modules/marketplace-apps.ts
- packages/contentstack-export/src/export/modules/personalize.ts
- packages/contentstack-import/src/import/modules/marketplace-apps.ts
- packages/contentstack-import/src/utils/entries-helper.ts
- packages/contentstack-variants/src/import/project.ts
- packages/contentstack-variants/src/import/variant-entries.ts
- packages/contentstack-variants/src/messages/index.ts
- packages/contentstack-variants/src/types/variant-entry.ts
- packages/contentstack-variants/src/utils/attributes-helper.ts
- packages/contentstack-variants/src/utils/error-helper.ts
- packages/contentstack-variants/src/utils/logger.ts
> fix: logger, custom attribute ref & error

- packages/contentstack-config/src/interfaces/index.ts
- packages/contentstack-config/src/utils/rate-limit-handler.ts
update rate limits accordingly
display the updated limits after setting
> fix: update rate limits accordingly

- package-lock.json
- packages/contentstack-branches/README.md
- packages/contentstack-branches/package.json
- packages/contentstack-clone/package.json
- packages/contentstack-config/README.md
- packages/contentstack-config/package.json
- packages/contentstack-export/README.md
- packages/contentstack-export/package.json
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
- @contentstack/cli-config: 1.7.1 -> 1.8.0
- @contentstack/cli-cm-branches: 1.1.3 -> 1.1.4
- @contentstack/cli-cm-export: 1.12.1 -> 1.12.2
> version bump

- package-lock.json
- packages/contentstack-export-to-csv/package.json
- packages/contentstack-export-to-csv/test/unit/commands/export-to-csv.test.js
- packages/contentstack-export-to-csv/test/util/common-utils.test.js
- packages/contentstack-export-to-csv/test/util/index.test.js
- updated all export to csv test cases
- updated package.json to run test for test/util folder
> dx | 1183 export to csv

- package-lock.json
- packages/contentstack-bulk-publish/README.md
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-bulk-publish/src/consumer/publish.js
- packages/contentstack-bulk-publish/src/producer/add-fields.js
- packages/contentstack-bulk-publish/src/producer/cross-publish.js
- packages/contentstack-bulk-publish/src/producer/nonlocalized-field-changes.js
- packages/contentstack-bulk-publish/src/producer/publish-edits.js
- packages/contentstack-bulk-publish/src/producer/publish-unpublished-env.js
- packages/contentstack-bulk-publish/src/producer/revert.js
- packages/contentstack-bulk-publish/src/producer/unpublish.js
- packages/contentstack-migration/README.md
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
> feat: implemented config rate limit in cross publish, unPublish , draft entries, adding new field to CT & revert

- package-lock.json
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-bulk-publish/src/producer/unpublish.js
- packages/contentstack/package.json
- pnpm-lock.yaml
> DX - 1911 - fix: added the check to only unpublish the filtered entries

- package-lock.json
- packages/contentstack-launch/README.md
- packages/contentstack-launch/package.json
- packages/contentstack-launch/src/graphql/queries.ts
- packages/contentstack-launch/src/util/logs-polling-utilities.ts
- packages/contentstack/package.json
- pnpm-lock.yaml
> fix: server response error while trying to fetch server logs

- .github/workflows/release.yml
- package-lock.json
- packages/contentstack/README.md
- packages/contentstack/package.json
update work flow and version bump 1.35.0
> update work flow and version bump (06-02-2025)

- package-lock.json
- packages/contentstack-audit/package.json
- packages/contentstack-auth/package.json
- packages/contentstack-bootstrap/package.json
- packages/contentstack-branches/package.json
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-clone/package.json
- packages/contentstack-command/package.json
- packages/contentstack-config/package.json
- packages/contentstack-export-to-csv/package.json
- packages/contentstack-export/example_config/auth_config.json
- packages/contentstack-export/example_config/management_config.json
- packages/contentstack-export/package.json
- packages/contentstack-import-setup/package.json
- packages/contentstack-import/example_config/auth_config.json
- packages/contentstack-import/example_config/management_config.json
- packages/contentstack-import/package.json
- packages/contentstack-migrate-rte/package.json
- packages/contentstack-migration/package.json
- packages/contentstack-seed/package.json
- packages/contentstack-utilities/package.json
- packages/contentstack-utilities/src/contentstack-management-sdk.ts
- packages/contentstack-variants/package.json
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump
contentstack/cli-utilities 1.8.1 -> 1.8.2
contentstack/cli 1.35.2 -> 1.35.3
> DX | 27-02-2025 | Hotfix

- package-lock.json
- packages/contentstack-audit/package.json
- packages/contentstack-auth/package.json
- packages/contentstack-bootstrap/package.json
- packages/contentstack-branches/package.json
- packages/contentstack-bulk-publish/package.json
- packages/contentstack-clone/package.json
- packages/contentstack-command/package.json
- packages/contentstack-config/package.json
- packages/contentstack-export-to-csv/package.json
- packages/contentstack-export/package.json
- packages/contentstack-import-setup/package.json
- packages/contentstack-import/package.json
- packages/contentstack-migrate-rte/package.json
- packages/contentstack-migration/package.json
- packages/contentstack-seed/package.json
- packages/contentstack-utilities/package.json
- packages/contentstack-utilities/src/helpers.ts
- packages/contentstack-variants/package.json
- packages/contentstack/README.md
- packages/contentstack/package.json
- pnpm-lock.yaml
@contentstack/cli 1.35.4 -> 1.35.5
@contentstack/cli-utilities: 1.8.3 -> 1.8.4
> fix: Expected 'source' to be a string, but received an object.

- package-lock.json
- packages/contentstack-audit/package.json
- packages/contentstack-audit/src/modules/content-types.ts
- packages/contentstack-import/package.json
- packages/contentstack/package.json
- pnpm-lock.yaml
version bump: 1.12.0 -> 1.12.1
> Fixed removal of fields that contain references
